#!/usr/bin/env node
/**
 * Claws MCP Server — expose terminal control as native Claude Code tools.
 * Zero dependencies. Node.js stdlib only.
 *
 * Powered by Claude Opus.
 *
 * Install Claws (auto-registers this MCP server globally):
 *     bash <(curl -fsSL https://raw.githubusercontent.com/neunaha/claws/main/scripts/install.sh)
 *
 * Or register manually (use FULL absolute path):
 *     "mcpServers": {
 *         "claws": {
 *             "command": "node",
 *             "args": ["/home/YOUR_USER/.claws-src/mcp_server.js"]
 *         }
 *     }
 *
 * Tools: claws_list, claws_create, claws_send, claws_exec,
 *        claws_read_log, claws_poll, claws_close, claws_worker,
 *        claws_hello, claws_subscribe, claws_publish, claws_broadcast,
 *        claws_ping, claws_peers
 */

const net = require('net');
const fs = require('fs');
const path = require('path');
const os = require('os');
const { randomUUID } = require('crypto');

// Guard: schemas/mcp-tools.json is generated by `npm run schemas` in extension/.
// If missing, fail fast with a clear message rather than a confusing crash.
const _mcpToolsPath = path.join(__dirname, 'schemas', 'mcp-tools.json');
if (!fs.existsSync(_mcpToolsPath)) {
  process.stderr.write(
    '[claws-mcp] ERROR: schemas/mcp-tools.json not found.\n' +
    '  Run: cd extension && npm run schemas\n',
  );
  process.exit(1);
}

// ─── MCP protocol (stdio, newline-delimited JSON) ──────────────────────────
// MCP spec: each JSON-RPC message is a single line on stdin/stdout, terminated
// by '\n'. (NOT LSP-style Content-Length framing — that was the prior bug.)

let inputBuf = '';

function readMessage() {
  return new Promise((resolve) => {
    const tryParse = () => {
      const nl = inputBuf.indexOf('\n');
      if (nl === -1) return false;
      const line = inputBuf.slice(0, nl).replace(/\r$/, '');
      inputBuf = inputBuf.slice(nl + 1);
      if (line.trim() === '') return tryParse();
      try {
        resolve(JSON.parse(line));
        return true;
      } catch {
        return tryParse();
      }
    };
    if (tryParse()) return;
    const onData = (chunk) => {
      inputBuf += chunk.toString('utf8');
      if (tryParse()) process.stdin.removeListener('data', onData);
    };
    process.stdin.on('data', onData);
  });
}

function writeMessage(msg) {
  process.stdout.write(JSON.stringify(msg) + '\n');
}

function respond(id, result) {
  writeMessage({ jsonrpc: '2.0', id, result });
}

function respondError(id, code, message) {
  writeMessage({ jsonrpc: '2.0', id, error: { code, message } });
}

function log(msg) {
  process.stderr.write('[claws-mcp] ' + msg + '\n');
}

function toolError(message) {
  return { content: [{ type: 'text', text: message }], isError: true };
}

// ─── Claws socket client ───────────────────────────────────────────────────

let counter = 0;

// Per-call socket — stateless claws/1 commands (list, create, send, close,
// readLog, poll, exec, introspect, ping, lifecycle.*). Each call opens a
// fresh socket, sends one frame, receives one response, destroys the socket.
function clawsRpc(sockPath, req, timeout = 30000) {
  return new Promise((resolve) => {
    counter++;
    req = { id: counter, ...req };
    const sock = net.createConnection(sockPath);
    sock.setTimeout(timeout);
    let buf = '';
    sock.on('connect', () => {
      sock.write(JSON.stringify(req) + '\n');
    });
    sock.on('data', (data) => {
      buf += data.toString('utf8');
      const nl = buf.indexOf('\n');
      if (nl !== -1) {
        try { resolve(JSON.parse(buf.slice(0, nl))); }
        catch { resolve({ ok: false, error: 'bad json from extension' }); }
        sock.destroy();
      }
    });
    sock.on('error', (err) => {
      log('socket error [' + req.cmd + ']: ' + err.message);
      resolve({ ok: false, error: `socket error: ${err.message}` });
      sock.destroy();
    });
    sock.on('timeout', () => {
      log('socket timeout [' + req.cmd + '] after ' + timeout + 'ms');
      resolve({ ok: false, error: 'socket timeout' });
      sock.destroy();
    });
  });
}

// ─── Persistent connection for stateful claws/2 commands ─────────────────────
// claws/2 peer state (registered by hello, consumed by publish/subscribe/
// broadcast/task.*) is bound to a single TCP connection on the server. Per-call
// sockets break multi-step flows: hello registers on socket A, then A is
// destroyed; the next call opens socket B which has no peer, and publish fails
// with "call hello first". One persistent socket is shared across all stateful
// tool calls for the lifetime of this MCP server process.

const _pconn = {
  socket: null,           // net.Socket | null
  pending: new Map(),     // rid → { resolve, reject, timer }
  buf: '',                // line-buffered receive buffer
  nextRid: 1_000_000,    // high range avoids collision with per-call counter
  peerId: null,           // allocated by server after successful hello
  role: null,             // cached for reconnect re-registration
  peerName: null,
  capabilities: null,
  sockPath: null,         // set on first successful connect
  connected: false,
};

// ─── Push-frame ring buffer ───────────────────────────────────────────────────
// Captures every push frame delivered on the persistent socket so the
// orchestrator can drain them via claws_drain_events without needing an active
// subscription loop.
const _eventBuffer = {
  ring: [],             // { absoluteIndex, topic, from, payload, sentAt, sequence }
  maxSize: 1000,        // evict oldest when full
  totalReceived: 0,     // monotonically increasing; used as cursor by callers
  waiters: [],          // { resolve, timer } registered by drain with wait_ms > 0
  maxWaiters: 10,       // cap: reject new wait_ms requests beyond this
  subscribed: false,    // true once we've sent hello + subscribe("**") on _pconn
  subscribeCursor: null, // event-log cursor at moment of subscription (Fix-D late-join detection)
  _overflowPending: false, // guards single system.bus.ring-overflow per eviction batch
  seenSequences: new Set(), // BUG-01: dedup frames delivered twice by overlapping subscriptions
};

let _pconnConnecting = null; // Promise | null — guards concurrent connect attempts
let _helloInFlight   = null; // Promise | null — deduplicates concurrent hello sends

// Circuit breaker for _pconnEnsureRegistered and _scanAndPublishCLAWSPUB.
// Prevents repeated expensive reconnect attempts when the extension socket is down.
const _circuitBreaker = {
  lastFailureTs: 0,       // epoch ms of most recent connect failure
  scanConsecutiveErrors: 0, // consecutive _scanAndPublishCLAWSPUB socket failures
  scanDisabled: false,    // true after 3 consecutive scan errors; reset on explicit reconnect
};

function _pconnHandleData(data) {
  _pconn.buf += data.toString('utf8');
  let nl;
  while ((nl = _pconn.buf.indexOf('\n')) !== -1) {
    const line = _pconn.buf.slice(0, nl);
    _pconn.buf = _pconn.buf.slice(nl + 1);
    if (!line.trim()) continue;
    try {
      const msg = JSON.parse(line);
      // Server encodes both `id` and `rid`; match on `rid` first.
      const rid = msg.rid != null ? msg.rid : msg.id;
      if (rid != null && _pconn.pending.has(rid)) {
        const { resolve, timer } = _pconn.pending.get(rid);
        clearTimeout(timer);
        _pconn.pending.delete(rid);
        resolve(msg);
      } else if (rid == null && (msg.push === 'message' || msg.topic != null)) {
        // BUG-01: skip duplicate delivery caused by overlapping subscriptions sharing a sequence.
        if (msg.sequence != null) {
          if (_eventBuffer.seenSequences.has(msg.sequence)) continue;
          _eventBuffer.seenSequences.add(msg.sequence);
          if (_eventBuffer.seenSequences.size > 2000) {
            const _seqArr = [..._eventBuffer.seenSequences];
            _eventBuffer.seenSequences = new Set(_seqArr.slice(-1000));
          }
        }
        // Push frame (no rid) — buffer for claws_drain_events.
        const entry = {
          absoluteIndex: ++_eventBuffer.totalReceived,
          topic: msg.topic || '',
          from: msg.from || '',
          payload: msg.payload != null ? msg.payload : null,
          sentAt: msg.sentAt || null,
          sequence: msg.sequence != null ? msg.sequence : null,
        };
        _eventBuffer.ring.push(entry);
        if (_eventBuffer.ring.length > _eventBuffer.maxSize) {
          _eventBuffer.ring.shift();
          // Emit ring-overflow once per eviction so callers know events were dropped.
          if (!_eventBuffer._overflowPending) {
            _eventBuffer._overflowPending = true;
            setImmediate(() => {
              _eventBuffer._overflowPending = false;
              const overflowEntry = {
                absoluteIndex: ++_eventBuffer.totalReceived,
                topic: 'system.bus.ring-overflow',
                from: 'mcp-server',
                payload: { droppedAt: new Date().toISOString(), ringSize: _eventBuffer.maxSize },
                sentAt: new Date().toISOString(),
                sequence: null,
              };
              _eventBuffer.ring.push(overflowEntry);
            });
          }
        }
        const woke = _eventBuffer.waiters.splice(0);
        for (const w of woke) { clearTimeout(w.timer); w.resolve(); }
      }
    } catch { /* ignore malformed frames */ }
  }
}

function _pconnHandleClose() {
  _pconn.connected = false;
  _pconn.socket = null;
  _pconn.buf = '';
  _pconn.peerId = null;
  _eventBuffer.subscribed = false; // reconnect requires fresh auto-subscribe
  for (const [, { reject, timer }] of _pconn.pending) {
    clearTimeout(timer);
    reject(new Error('persistent socket closed'));
  }
  _pconn.pending.clear();
  // Schedule reconnect; on success, re-issue hello if we had a prior identity.
  if (_pconn.sockPath) {
    const sp = _pconn.sockPath;
    setTimeout(async () => {
      try {
        await _pconnEnsure(sp);
        if (_pconn.role && !_pconn.peerId) {
          const resp = await _pconnWrite({
            cmd: 'hello', protocol: 'claws/2',
            role: _pconn.role, peerName: _pconn.peerName,
            capabilities: _pconn.capabilities || undefined,
          }, 5000);
          if (resp.ok) {
            _pconn.peerId = resp.peerId;
            log(`reconnected and re-registered as ${resp.peerId} role=${_pconn.role}`);
          }
        }
      } catch { /* reconnect failed; next stateful call will retry */ }
    }, 1000);
  }
}

function _pconnConnect(sockPath) {
  return new Promise((resolve, reject) => {
    const sock = net.createConnection(sockPath);
    // M-50: 5s connect timeout — prevents _pconnConnect from hanging forever
    // when the extension socket exists but VS Code is reloading (ECONNREFUSED
    // can take arbitrarily long on some platforms without a ceiling).
    sock.setTimeout(5000);
    sock.on('timeout', () => sock.destroy(new Error('persistent socket connect timed out')));
    sock.on('connect', () => {
      sock.setTimeout(0); // clear connect-phase timeout once connected
      _pconn.socket = sock;
      _pconn.sockPath = sockPath;
      _pconn.connected = true;
      resolve();
    });
    sock.on('data', _pconnHandleData);
    sock.on('error', (err) => {
      if (!_pconn.connected) {
        reject(err);
      } else {
        log('persistent socket error: ' + err.message);
      }
    });
    sock.on('close', _pconnHandleClose);
  });
}

function _pconnEnsure(sockPath) {
  if (_pconn.connected) return Promise.resolve();
  if (_pconnConnecting) return _pconnConnecting;
  _pconnConnecting = _pconnConnect(sockPath).finally(() => { _pconnConnecting = null; });
  return _pconnConnecting;
}

function _pconnWrite(req, timeout) {
  return new Promise((resolve, reject) => {
    if (!_pconn.socket || !_pconn.connected) {
      return reject(new Error('persistent socket not connected'));
    }
    const rid = _pconn.nextRid++;
    const ms = timeout || 30000;
    const timer = setTimeout(() => {
      _pconn.pending.delete(rid);
      reject(new Error('stateful socket timeout'));
    }, ms);
    _pconn.pending.set(rid, { resolve, reject, timer });
    try {
      // Stateful commands route via taskId/assignee/subscriptionId/peerId — never 'id'.
      // Explicitly drop any user-supplied 'id' before stamping the RPC correlation id,
      // so a future command carrying 'id' as a routing field cannot be silently misrouted.
      const { id: _discarded, ...reqBody } = req;
      _pconn.socket.write(JSON.stringify({ ...reqBody, id: rid }) + '\n');
    } catch (err) {
      clearTimeout(timer);
      _pconn.pending.delete(rid);
      reject(err);
    }
  });
}

// Persistent-socket RPC for stateful claws/2 commands. Connects the persistent
// socket on first call; reuses it for all subsequent calls.
async function clawsRpcStateful(sockPath, req, timeout) {
  try {
    await _pconnEnsure(sockPath);
  } catch (err) {
    return { ok: false, error: `persistent socket connect failed: ${err.message}` };
  }
  try {
    return await _pconnWrite(req, timeout);
  } catch (err) {
    return { ok: false, error: `persistent socket error: ${err.message}` };
  }
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

async function fileExec(sockPath, termId, command, timeoutMs = 180000) {
  const execId = randomUUID().slice(0, 10);
  const base = path.join(os.tmpdir(), 'claws-exec');
  fs.mkdirSync(base, { recursive: true });
  const outPath = path.join(base, `${execId}.out`);
  const donePath = path.join(base, `${execId}.done`);
  const wrapper = `{ ${command}; } > ${outPath} 2>&1; echo $? > ${donePath}`;
  await clawsRpc(sockPath, { cmd: 'send', id: termId, text: wrapper, newline: true });
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (fs.existsSync(donePath)) break;
    await sleep(150);
  }
  if (!fs.existsSync(donePath)) {
    const partial = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : '';
    return { ok: false, error: `timeout after ${timeoutMs}ms`, partial };
  }
  const exitRaw = fs.readFileSync(donePath, 'utf8').trim();
  const exitCode = /^\d+$/.test(exitRaw) ? parseInt(exitRaw, 10) : null;
  const output = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : '';
  try { fs.unlinkSync(outPath); } catch {}
  try { fs.unlinkSync(donePath); } catch {}
  return { ok: true, terminal_id: termId, command, output, exit_code: exitCode };
}

// ─── Tool definitions (generated — run: cd extension && npm run schemas) ──────

const TOOLS = require('./schemas/mcp-tools.json');

// ─── Blocking worker lifecycle ─────────────────────────────────────────────

function escapeRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// Find marker only when it appears in tool/output context — never in prose.
// Real Claude pty patterns the matcher MUST accept:
//   • bare-shell printf:        "MARKER\n"
//   • Claude text response:     "⏺MARKER<trailing-spaces>\r…"
//   • Claude tool-result line:  "  ⎿  MARKER\r…"
// Prose collisions the matcher MUST reject:
//   • mission restatement:      "step 4. Echo MARKER on its own line."
//   • shell command echo:       "% echo MARKER"
//   • Claude action header:     "⏺Bash(echo 'MARKER')" — wait for the actual
//                                tool result instead, never false-complete on
//                                a Bash command that hasn't run yet.
// Anchor: line start → optional whitespace → optional ⏺/⎿ indicator →
//         optional whitespace → exact marker → whitespace/newline/EOT.
function findStandaloneMarker(text, marker) {
  if (!marker || typeof marker !== 'string' || !text) return null;
  const re = new RegExp(
    '(?:^|[\\r\\n])[\\t ]*[⏺⎿]?[\\t ]*' + escapeRegex(marker) + '(?=[\\t \\r\\n]|$)'
  );
  const m = re.exec(text);
  if (m === null) return null;
  const ls = text.lastIndexOf('\n', m.index);
  const lineStart = ls === -1 ? 0 : ls + 1;
  const lineEnd = text.indexOf('\n', lineStart);
  return text.slice(lineStart, lineEnd === -1 ? text.length : lineEnd).trim();
}

// Backward-compat alias — internal callsites should prefer findStandaloneMarker.
function findMarkerLine(text, marker) {
  return findStandaloneMarker(text, marker);
}

// ─── [CLAWS_PUB] line scanner ─────────────────────────────────────────────────
// SDK-less workers print [CLAWS_PUB] topic=<topic> key=val ... lines to stdout.
// The MCP server scans new pty output for these markers each poll tick and
// publishes on the worker's behalf — no socket, peerId, or SDK required.
// Grammar:  [CLAWS_PUB] topic=<topic> key1=val key2="quoted val" key3=42
// Values:   "..." → string  |  true/false → boolean  |  digits → number
async function _scanAndPublishCLAWSPUB(newText, sockPath) {
  // Circuit breaker: if 3 consecutive socket errors, stop scanning until reconnect.
  if (_circuitBreaker.scanDisabled) return;
  const MARKER_RE = /^\[CLAWS_PUB\]\s+topic=(\S+)\s*(.*)?$/;
  const KV_RE = /(\w+)=("([^"]*)"|(\S+))/g;
  for (const line of newText.split('\n')) {
    const m = MARKER_RE.exec(line);
    if (!m) continue;
    const topic = m[1];
    const rest = m[2] || '';
    const payload = {};
    KV_RE.lastIndex = 0;
    let kv;
    while ((kv = KV_RE.exec(rest)) !== null) {
      const key = kv[1];
      const rawVal = kv[3] !== undefined ? kv[3] : kv[4];
      if (rawVal === 'true') payload[key] = true;
      else if (rawVal === 'false') payload[key] = false;
      else if (/^-?\d+(\.\d+)?$/.test(rawVal)) payload[key] = parseFloat(rawVal);
      else payload[key] = rawVal;
    }
    try {
      await _pconnEnsureRegistered(sockPath);
      await _pconnWrite({ cmd: 'publish', protocol: 'claws/2', topic, payload }, 3000);
      _circuitBreaker.scanConsecutiveErrors = 0;
    } catch (e) {
      _circuitBreaker.scanConsecutiveErrors++;
      log('[CLAWS_PUB] publish failed topic=' + topic + ': ' + (e && e.message || e));
      if (_circuitBreaker.scanConsecutiveErrors >= 3) {
        _circuitBreaker.scanDisabled = true;
        log('[CLAWS_PUB] circuit breaker tripped after 3 consecutive socket errors — scan disabled until reconnect');
        return;
      }
    }
  }
}

async function runBlockingWorker(sock, args) {
  const DEFAULTS = {
    timeout_ms: 5 * 60 * 1000,
    boot_wait_ms: 8000,
    // v0.7.9: was 'Claude Code' (with a space) — never matched the ANSI-stripped
    // Claude Code v2.x banner ("ClaudeCodev2.1.123" — no space). Worker burned the
    // full boot_wait_ms on every spawn before falling through. 'bypass permissions'
    // is in the bypass-mode footer/banner and matches reliably.
    boot_marker: 'bypass permissions',
    complete_marker: 'MISSION_COMPLETE',
    error_markers: ['MISSION_FAILED'],
    poll_interval_ms: 1500,
    harvest_lines: 200,
    close_on_complete: true,
    model: 'claude-sonnet-4-6',
  };
  const opt = { ...DEFAULTS, ...args };
  if (!/^[a-zA-Z0-9._-]+$/.test(opt.model)) {
    return { status: 'error', error: `invalid model name '${opt.model}' — must match /^[a-zA-Z0-9._-]+$/` };
  }
  const hasMission = typeof args.mission === 'string' && args.mission.length > 0;
  const hasCommand = typeof args.command === 'string' && args.command.length > 0;
  const launchClaude = args.launch_claude !== undefined
    ? !!args.launch_claude
    : hasMission;
  // Default cwd to the MCP server's working directory (project root) so workers
  // never land in $HOME — which would trigger the trust dialog and break the
  // project MCP socket walk-up. Caller may override.
  const workerCwd = typeof args.cwd === 'string' && args.cwd.length > 0
    ? args.cwd
    : process.cwd();

  // 1. Create wrapped terminal
  const cr = await clawsRpc(sock, {
    cmd: 'create', name: args.name || 'claws-worker', wrapped: true, show: true,
    cwd: workerCwd, env: { CLAWS_WORKER: '1' },
  });
  if (!cr.ok) return { status: 'error', error: `create failed: ${_lifecycleErrMsg(cr.error)}` };
  const termId = cr.id;
  const _bCorrId = randomUUID();
  const startedAt = Date.now();

  // Publish system.worker.spawned — best-effort, never aborts on failure.
  log(`runBlockingWorker: publishing system.worker.spawned for terminal ${termId}`);
  try {
    await _pconnEnsureRegistered(sock);
    await _pconnWrite({
      cmd: 'publish', protocol: 'claws/2',
      topic: 'system.worker.spawned',
      payload: { terminal_id: termId, name: args.name || 'claws-worker', wrapped: true, started_at: new Date(startedAt).toISOString(), correlation_id: _bCorrId },
    });
    log(`runBlockingWorker: system.worker.spawned published ok for terminal ${termId}`);
  } catch (e) { log('runBlockingWorker: system.worker.spawned publish FAILED: ' + (e && e.message || e)); }

  // D+F: register spawn + monitor atomically before proceeding. Best-effort (lifecycle may not be in active mission).
  try { await clawsRpc(sock, { cmd: 'lifecycle.register-spawn', terminalId: String(termId), correlationId: _bCorrId, name: args.name || 'claws-worker' }); } catch (e) { /* non-fatal */ }
  const _bMonitorCmd = `Monitor(command="CLAWS_TOPIC='system.worker.*' CLAWS_PEER_NAME='monitor-term-${termId}' CLAWS_ROLE='observer' node ${path.join(path.dirname(path.resolve(sock)), '..', 'scripts', 'stream-events.js')} 2>&1 | grep --line-buffered '\\"correlation_id\\":\\"${_bCorrId}\\"' | grep --line-buffered -m1 'system\\\\.worker\\\\.completed'", description="claws monitor | term=${termId} | corr=${_bCorrId.slice(0,8)} | sess=${new Date().toISOString().slice(0,13)}", timeout_ms=600000, persistent=false)`;
  try { await clawsRpc(sock, { cmd: 'lifecycle.register-monitor', terminalId: String(termId), correlationId: _bCorrId, command: _bMonitorCmd }); } catch (e) { /* non-fatal */ }

  // 2. Give shell a moment to emit prompt
  await sleep(400);

  // 3. Optional claude boot + detection — single attempt, best-effort.
  // Sends the launch command ONCE, polls for the boot marker for up to
  // boot_wait_ms, then proceeds whether or not the marker matched. There is
  // intentionally no retry: if the boot marker isn't found, sending the launch
  // command a second time would type "claude ..." into an already-booted
  // Claude Code TUI as a user prompt, which is harmful and confusing.
  let booted = !launchClaude;
  if (launchClaude) {
    await clawsRpc(sock, {
      cmd: 'send', id: termId,
      text: `claude --dangerously-skip-permissions --model ${opt.model}`, newline: true,
    });
    // Event-driven READINESS detection: ❯ alone exits too early — Claude's
    // React/Ink renders the input prompt before MCP auth + render pipeline
    // are finalized. Stricter check: require BOTH ❯ AND `cost:$` (cost line
    // at bottom — only appears when Claude is fully idle and receptive).
    // Stable for 3 polls (~900ms) before declaring ready.
    const bootDeadline = Date.now() + opt.boot_wait_ms;
    let _promptStableCount = 0;
    while (Date.now() < bootDeadline) {
      const snap = await clawsRpc(sock, {
        cmd: 'readLog', id: termId, strip: true, limit: 32 * 1024,
      });
      const _bytes = (snap.ok && typeof snap.bytes === 'string') ? snap.bytes : '';
      // Require: input prompt (❯) AND idle indicator (cost:$ shown only when ready)
      const _hasPrompt = _bytes.includes('❯');
      const _hasCostLine = _bytes.includes('cost:$') || _bytes.includes('cost: $');
      if (_hasPrompt && _hasCostLine) {
        _promptStableCount++;
        if (_promptStableCount >= 3) { booted = true; break; }
      } else {
        _promptStableCount = 0;
      }
      await sleep(300);
    }
    // BUG-07: secondary MCP auth check — bypass banner can appear before /mcp auth resolves.
    if (booted) {
      const _authSnap = await clawsRpc(sock, { cmd: 'readLog', id: termId, strip: true, limit: 32 * 1024 });
      if (_authSnap.ok && typeof _authSnap.bytes === 'string' &&
          (_authSnap.bytes.includes('MCP server need') || _authSnap.bytes.includes(' /mcp'))) {
        if (opt.close_on_complete) try { await clawsRpc(sock, { cmd: 'close', id: termId }); } catch {}
        return { status: 'error', error: `boot_marker seen but MCP auth banner active on terminal ${termId} — prompt is blocked. Spawn with minimal MCP config or pre-auth.` };
      }
    }
    // Proceed even if marker missed — best-effort. Some users may have
    // customized the Claude Code TUI banner; the actual launch may have worked.
    // POST-BOOT SETTLE: even after ❯ + cost:$ visible, Claude has a hidden async
    // window (~5s) during which paste-submit gestures get lost. Manual claws_send
    // testing proves 18s total wait works; programmatic boot is ~6.5s, so 5000ms
    // extra settle brings us to ~11s — empirically reliable.
    await sleep(5000);
  }

  // 4. Send the mission AS A USER PROMPT — direct, the way it works in v0.7.4.
  // ──────────────────────────────────────────────────────────────────────────
  // No file abstractions. The user's mission text becomes Claude Code's input
  // exactly as if a human typed it, because that's what users expect.
  //
  // DO NOT add a file-referrer pattern here. If a future contributor is tempted
  // to write the mission to /tmp and send a "Read <file>..." referrer to dodge
  // some pty quirk, the answer is NO. The mission is a user prompt. Period.
  // Strip bracketed-paste escape sequences so a crafted mission cannot break out of paste mode.
  const safeMission = hasMission
    ? args.mission.replace(/\x1b\[200~/g, '').replace(/\x1b\[201~/g, '')
    : args.mission;
  // ROOT CAUSE FIX (2026-05-02): mission augmentation with CLAWS_PUB preamble was
  // breaking Claude TUI multi-line submission. Preamble added ~5 extra lines +
  // special chars (single quotes around topics), pushing total text past Claude's
  // paste-collapse threshold. Multi-line input rendered expanded; single \r
  // treated as newline-within-input, never submitted.
  // Verified: identical mission via claws_send (no augmentation) submits ✓.
  // Send mission DIRECTLY, no preamble.
  const payload = hasMission ? safeMission
                : hasCommand ? args.command
                : '';

  if (payload) {
    if (launchClaude) {
      // Bracketed paste + writeInjected internal 30ms CR.
      // VERIFIED 2026-05-02 by manual claws_create + claws_send test:
      //   • single-line: paste:true + newline:true → text wrapped in
      //     \x1b[200~...\x1b[201~, then \r 30ms later → SUBMITS ✓
      //   • multi-line:  same pattern → SUBMITS ✓ (Claude paste-collapses or
      //     accepts whole bracketed paste atomically; \r 30ms later submits)
      //
      // Without paste:true, multi-line text is typed raw and each \n becomes
      // newline-within-input (Claude's multi-line input mode). Single \r at
      // end then ALSO becomes newline-within-input, never submitting.
      await clawsRpc(sock, { cmd: 'send', id: termId, text: payload, newline: true, paste: true });
    } else {
      // Bare shell command: no paste needed; trailing \n submits via the prompt.
      await clawsRpc(sock, { cmd: 'send', id: termId, text: payload, newline: true });
    }
  }

  // Bulletproof marker scan offset: poll for TUI evidence that the mission
  // was acknowledged (paste-collapse placeholder, thinking spinner, or
  // significant buffer growth past pre-send length), then capture offset.
  // The 400ms fixed sleep was timing-fragile — Claude Code v2.x sometimes
  // delays input echo past that window.
  // BUG-26: settle scan is Claude TUI boot detection only. For bare shell
  // commands (launch_claude=false) the complete_marker may print before the
  // first poll tick — setting markerScanFrom past the marker causes the detach
  // watcher to never find it. Skip settle for non-Claude paths; markerScanFrom
  // stays 0 so the watcher scans the full log from the start.
  let markerScanFrom = 0;
  if (launchClaude) {
    try {
      const preSnap = await clawsRpc(sock, { cmd: 'readLog', id: termId, strip: true, limit: 64 * 1024 });
      const preLen = (preSnap.ok && typeof preSnap.bytes === 'string') ? preSnap.bytes.length : 0;
      const settleDeadline = Date.now() + 5000;
      const settleIndicator = /Pasted text|tokens|thinking|Synthesizing|Combobulating|Prestidigitating|Brewed|Cogitated|Crunched|Ideating/;
      while (Date.now() < settleDeadline) {
        await sleep(200);
        const snap = await clawsRpc(sock, { cmd: 'readLog', id: termId, strip: true, limit: 64 * 1024 });
        if (snap.ok && typeof snap.bytes === 'string') {
          const text = snap.bytes;
          const newRegion = text.slice(preLen);
          if (text.length > preLen + 200 || settleIndicator.test(newRegion)) {
            markerScanFrom = text.length;
            break;
          }
        }
      }
      if (markerScanFrom === 0) {
        const finalSnap = await clawsRpc(sock, { cmd: 'readLog', id: termId, strip: true, limit: 64 * 1024 });
        if (finalSnap.ok && typeof finalSnap.bytes === 'string') {
          markerScanFrom = finalSnap.bytes.length;
        }
      }
    } catch (e) { /* keep markerScanFrom=0; degraded but not fatal */ }
  }

  // 5. Detach shortcut — register background watcher that runs the SAME poll
  // body as the blocking path so [CLAWS_PUB] scanner, system.worker.completed
  // publish, and auto-close all keep working in detach mode. Server-side only,
  // never holds the MCP socket.
  if (args.detach === true) {
    let pubScanOffset = markerScanFrom;
    let status = 'timeout';
    let markerLine = null;
    const timeoutDeadline = startedAt + opt.timeout_ms;
    const tick = async () => {
      try {
        if (Date.now() > timeoutDeadline) {
          clearInterval(intervalId);
          _detachWatchers.delete(termId);
          try {
            await _pconnEnsureRegistered(sock);
            await _pconnWrite({
              cmd: 'publish', protocol: 'claws/2',
              topic: 'system.worker.completed',
              payload: { terminal_id: termId, status, duration_ms: Date.now() - startedAt, marker_line: markerLine, booted, detach: true, correlation_id: _bCorrId },
            });
          } catch (e) { log('detach watcher publish failed: ' + (e && e.message || e)); }
          try { await clawsRpc(sock, { cmd: 'lifecycle.mark-worker-status', terminalId: String(termId), status: 'timeout' }); } catch (e) { /* non-fatal */ }
          return;
        }
        const snap = await clawsRpc(sock, { cmd: 'readLog', id: termId, strip: true, limit: 64 * 1024 });
        const text = snap.ok && typeof snap.bytes === 'string' ? snap.bytes : '';
        const scanText = text.length > markerScanFrom ? text.slice(markerScanFrom) : '';
        const scanStart = Math.min(pubScanOffset, text.length);
        if (text.length > scanStart) await _scanAndPublishCLAWSPUB(text.slice(scanStart), sock);
        pubScanOffset = text.length;
        const _completeLine = findStandaloneMarker(scanText, opt.complete_marker);
        if (_completeLine !== null) {
          status = 'completed';
          markerLine = _completeLine;
        } else {
          for (const em of opt.error_markers) {
            const _errLine = em ? findStandaloneMarker(scanText, em) : null;
            if (_errLine !== null) { status = 'failed'; markerLine = _errLine; break; }
          }
        }
        if (status !== 'timeout') {
          clearInterval(intervalId);
          _detachWatchers.delete(termId);
          try {
            await _pconnEnsureRegistered(sock);
            await _pconnWrite({
              cmd: 'publish', protocol: 'claws/2',
              topic: 'system.worker.completed',
              payload: { terminal_id: termId, status, duration_ms: Date.now() - startedAt, marker_line: markerLine, booted, detach: true, correlation_id: _bCorrId },
            });
          } catch (e) { log('detach watcher publish failed: ' + (e && e.message || e)); }
          try { await clawsRpc(sock, { cmd: 'lifecycle.mark-worker-status', terminalId: String(termId), status }); } catch (e) { /* non-fatal */ }
          if (opt.close_on_complete !== false) {
            try { await clawsRpc(sock, { cmd: 'close', id: termId }); } catch {}
          }
        }
      } catch (e) { log('detach watcher tick error: ' + (e && e.message || e)); }
    };
    const intervalId = setInterval(tick, opt.poll_interval_ms);
    _detachWatchers.set(termId, { intervalId, opt, startedAt });
    return { status: 'spawned', terminal_id: termId, booted, duration_ms: Date.now() - startedAt, correlation_id: _bCorrId };
  }

  // 6. Poll for completion / errors / timeout
  const timeoutDeadline = startedAt + opt.timeout_ms;
  let status = 'timeout';
  let markerLine = null;
  let pubScanOffset = markerScanFrom; // start CLAWS_PUB scan from the same offset
  while (Date.now() < timeoutDeadline) {
    const snap = await clawsRpc(sock, {
      cmd: 'readLog', id: termId, strip: true, limit: 64 * 1024,
    });
    const text = snap.ok && typeof snap.bytes === 'string' ? snap.bytes : '';

    // Only scan bytes produced AFTER the payload was sent + echoed. This
    // prevents the marker substring from false-matching on the input echo
    // of the user's mission text.
    const scanText = text.length > markerScanFrom ? text.slice(markerScanFrom) : '';

    // Scan lines added since the last poll tick for [CLAWS_PUB] publish markers.
    const scanStart = Math.min(pubScanOffset, text.length);
    if (text.length > scanStart) {
      await _scanAndPublishCLAWSPUB(text.slice(scanStart), sock);
    }
    pubScanOffset = text.length;

    const _bCompleteLine = findStandaloneMarker(scanText, opt.complete_marker);
    if (_bCompleteLine !== null) {
      status = 'completed';
      markerLine = _bCompleteLine;
      break;
    }
    let failed = false;
    for (const em of opt.error_markers) {
      const _bErrLine = em ? findStandaloneMarker(scanText, em) : null;
      if (_bErrLine !== null) {
        status = 'failed';
        markerLine = _bErrLine;
        failed = true;
        break;
      }
    }
    if (failed) break;

    await sleep(opt.poll_interval_ms);
  }

  // Publish system.worker.completed — best-effort, never aborts on failure.
  try {
    await _pconnEnsureRegistered(sock);
    await _pconnWrite({
      cmd: 'publish', protocol: 'claws/2',
      topic: 'system.worker.completed',
      payload: { terminal_id: termId, status, duration_ms: Date.now() - startedAt, marker_line: markerLine, booted, correlation_id: _bCorrId },
    });
  } catch (e) { log('system.worker.completed publish failed: ' + (e && e.message || e)); }
  try { await clawsRpc(sock, { cmd: 'lifecycle.mark-worker-status', terminalId: String(termId), status }); } catch (e) { /* non-fatal */ }

  // 7. Harvest final output
  const final = await clawsRpc(sock, {
    cmd: 'readLog', id: termId, strip: true, limit: 256 * 1024,
  });
  const allLines = (final.ok && typeof final.bytes === 'string' ? final.bytes : '').split('\n');
  const harvest = allLines.slice(-opt.harvest_lines).join('\n');

  // 8. Auto-close
  let cleanedUp = false;
  if (opt.close_on_complete) {
    const cl = await clawsRpc(sock, { cmd: 'close', id: termId });
    cleanedUp = !!cl.ok;
  }

  return {
    status,
    terminal_id: termId,
    booted,
    duration_ms: Date.now() - startedAt,
    marker_line: markerLine,
    cleaned_up: cleanedUp,
    harvest,
    correlation_id: _bCorrId,
  };
}

// ─── Sidecar auto-spawn ───────────────────────────────────────────────────────
let _sidecarPid        = null;
let _sidecarSubscribed = false; // true only after sidecar.subscribed JSON confirmed
let _sidecarStdout     = null;  // kept open to prevent SIGPIPE
let _sidecarEnsureInFlight = null; // singleton in-flight Promise dedup

function _isSidecarAlive() {
  if (!_sidecarPid || !_sidecarSubscribed) return false;
  try { process.kill(_sidecarPid, 0); return true; } catch { return false; }
}

async function _spawnAndVerifySidecar(maxWaitMs = 3000) {
  const { spawn, spawnSync } = require('child_process');
  // BUG-19 fix: __dirname resolves to repo root when .claws-bin/mcp_server.js is symlinked
  // back to ../mcp_server.js (Wave A's dedup). Try multiple candidate locations.
  const sidecarCandidates = [
    path.join(__dirname, 'stream-events.js'),                  // .claws-bin layout (non-symlinked install)
    path.join(__dirname, '.claws-bin', 'stream-events.js'),    // repo root + .claws-bin
    path.join(__dirname, 'scripts', 'stream-events.js'),       // repo root + scripts (dev source)
  ];
  const sidecarPath = sidecarCandidates.find(p => fs.existsSync(p));
  if (!sidecarPath) throw new Error('stream-events.js not found in any candidate: ' + sidecarCandidates.join(', '));

  // GAP-A1: detect existing auto-sidecar (spawned by session-start hook) to avoid
  // two concurrent sidecars both writing to events.log, causing 4x event duplication.
  const socketPath = getSocket();
  const escapedSocket = socketPath.replace(/[.+?^${}()|[\]\\]/g, '\\$&');
  const pgResult = spawnSync('pgrep', ['-f', `stream-events\\.js.*--auto-sidecar.*${escapedSocket}`], { encoding: 'utf8' });
  if (pgResult.status === 0) {
    const existingPid = parseInt((pgResult.stdout || '').trim().split('\n')[0], 10);
    if (!isNaN(existingPid)) {
      log(`[sidecar] adopting existing auto-sidecar pid=${existingPid} (GAP-A1 dedup)`);
      _sidecarPid        = existingPid;
      _sidecarSubscribed = true;
      return;
    }
  }

  // Open events.log for appending — after verification confirmed, stdout is
  // piped here so every sidecar push frame is persisted for tail-F monitoring.
  const eventsLogDir = path.dirname(path.resolve(socketPath));
  const eventsLogFilePath = path.join(eventsLogDir, 'events.log');
  const eventsLogStream = fs.createWriteStream(eventsLogFilePath, { flags: 'a' });

  // GAP-A1: pass --auto-sidecar + socketPath as args so session-start pgrep can detect us.
  const child = spawn(process.execPath, [sidecarPath, '--auto-sidecar', socketPath], {
    detached: true,
    stdio: ['ignore', 'pipe', 'ignore'],
    env: { ...process.env, CLAWS_TOPIC: '**', CLAWS_PEER_NAME: 'auto-sidecar', CLAWS_ROLE: 'observer' },
  });

  if (!child.pid) throw new Error('sidecar spawn returned no pid (ENOENT or permission denied)');
  _sidecarPid    = child.pid;
  _sidecarStdout = child.stdout;

  // Named drain — removed after verification so stdout can be piped to events.log.
  function drainHandler() {}
  child.stdout.on('data', drainHandler);
  child.on('exit', (code) => {
    log(`[sidecar] exited code=${code}`);
    eventsLogStream.end();
    _sidecarPid        = null;
    _sidecarSubscribed = false;
    _sidecarStdout     = null;
  });

  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      child.stdout.removeListener('data', verifyHandler);
      reject(new Error(`sidecar did not reach SUBSCRIBED within ${maxWaitMs}ms`));
    }, maxWaitMs);

    let buf = '';
    function verifyHandler(chunk) {
      buf += chunk.toString('utf8');
      let nl;
      while ((nl = buf.indexOf('\n')) !== -1) {
        const line = buf.slice(0, nl); buf = buf.slice(nl + 1);
        try {
          const obj = JSON.parse(line);
          if (obj.type === 'sidecar.subscribed' && obj.ok !== false) {
            clearTimeout(timer);
            child.stdout.removeListener('data', verifyHandler);
            child.stdout.removeListener('data', drainHandler);
            child.stdout.pipe(eventsLogStream);
            child.unref();
            _sidecarSubscribed = true;
            log(`[sidecar] SUBSCRIBED confirmed — piping stdout to ${eventsLogFilePath}`);
            resolve();
            return;
          }
          if (obj.type === 'sidecar.error') {
            clearTimeout(timer);
            child.stdout.removeListener('data', verifyHandler);
            reject(new Error('sidecar error: ' + obj.error));
            return;
          }
        } catch { /* incomplete JSON line, skip */ }
      }
    }
    child.stdout.on('data', verifyHandler);

    child.on('exit', (code) => {
      clearTimeout(timer);
      child.stdout.removeListener('data', verifyHandler);
      if (code !== 0) reject(new Error(`sidecar crashed (exit ${code}) before reaching SUBSCRIBED`));
    });
  });
}

async function _ensureSidecarOrThrow(maxWaitMs = 3000) {
  if (_isSidecarAlive()) return;
  if (!_sidecarEnsureInFlight) {
    _sidecarEnsureInFlight = _spawnAndVerifySidecar(maxWaitMs)
      .finally(() => { _sidecarEnsureInFlight = null; });
  }
  await _sidecarEnsureInFlight;
}

// ─── Persistent-socket identity helper ────────────────────────────────────────
// Ensures the persistent socket is connected AND this process has a peerId.
// If not yet registered, sends hello with role=orchestrator, peerName=mcp-orchestrator.
// Called once per process lifetime in practice (peerId cached on _pconn).
async function _pconnEnsureRegistered(sockPath) {
  // 30s failure cache: skip reconnect attempt entirely if we failed recently.
  if (!_pconn.connected && _circuitBreaker.lastFailureTs > 0) {
    if (Date.now() - _circuitBreaker.lastFailureTs < 30_000) {
      throw new Error('circuit-breaker: last connect failed < 30s ago, skipping');
    }
  }
  try {
    await _pconnEnsure(sockPath);
  } catch (err) {
    _circuitBreaker.lastFailureTs = Date.now();
    throw err;
  }
  // Reset failure timestamp on successful connect.
  _circuitBreaker.lastFailureTs = 0;
  if (!_pconn.peerId) {
    if (!_helloInFlight) {
      _helloInFlight = _pconnWrite({
        cmd: 'hello', protocol: 'claws/2',
        role: 'orchestrator', peerName: 'mcp-orchestrator',
      }, 5000).finally(() => { _helloInFlight = null; });
    }
    const hr = await _helloInFlight;
    if (hr && hr.ok && !_pconn.peerId) {
      _pconn.peerId = hr.peerId;
      _pconn.role = 'orchestrator';
      _pconn.peerName = 'mcp-orchestrator';
      // Re-enable scan if it was disabled — explicit reconnect counts as resume.
      _circuitBreaker.scanDisabled = false;
      _circuitBreaker.scanConsecutiveErrors = 0;
      log('auto-registered as peer ' + hr.peerId + ' role=orchestrator');
    }
  }
}

// ─── Tool handlers ─────────────────────────────────────────────────────────

function getSocket() {
  // Absolute override wins immediately.
  const envSock = process.env.CLAWS_SOCKET;
  if (envSock && path.isAbsolute(envSock)) return envSock;

  // Walk up from CWD to find .claws/claws.sock — works when Claude Code chdir'd
  // to the workspace root before spawning the MCP server.
  for (let dir = process.cwd();;) {
    const candidate = path.join(dir, '.claws', 'claws.sock');
    try { if (fs.statSync(candidate).isSocket()) return candidate; } catch {}
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }

  // Walk up from __dirname — self-locating regardless of CWD.
  // Project install: .claws-bin/mcp_server.js -> parent = project root -> .claws/claws.sock
  // Global install: ~/.claws-src/mcp_server.js -> walks up, finds nothing, falls through.
  for (let dir = __dirname;;) {
    const candidate = path.join(dir, '.claws', 'claws.sock');
    try { if (fs.statSync(candidate).isSocket()) return candidate; } catch {}
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }

  // Fall back to env var (may be relative) or the conventional default.
  return envSock || '.claws/claws.sock';
}

const _detachWatchers = new Map(); // termId -> { intervalId, opt, startedAt }

// Safety guard: cap any single blocking tool response to 8 s over MCP stdio.
async function withMaxHold(promise, maxMs = 8000, partialBuilder) {
  let timer;
  const timeout = new Promise(r => { timer = setTimeout(() => r({ __maxHold: true }), maxMs); });
  const winner = await Promise.race([promise, timeout]);
  clearTimeout(timer);
  if (winner && winner.__maxHold) return partialBuilder();
  return winner;
}

// BUG-12: translate opaque lifecycle gate codes into actionable messages.
function _lifecycleErrMsg(rawErr) {
  if (typeof rawErr === 'string' && rawErr.startsWith('lifecycle:')) {
    return `lifecycle gate active (${rawErr}) — call claws_lifecycle_plan to start a new cycle before spawning new terminals`;
  }
  return rawErr;
}

async function handleTool(name, args) {
  const sock = getSocket();
  _ensureSidecarOrThrow(2000).catch(() => {}); // best-effort warm-up
  const _t0 = Date.now();
  try {
    await _pconnEnsureRegistered(sock);
    await _pconnWrite({ cmd: 'publish', protocol: 'claws/2', topic: `tool.${name}.invoked`, payload: { peerId: _pconn.peerId, args_keys: Object.keys(args) } });
  } catch (_pe) { /* best-effort */ }
  let _r;
  try {
    _r = await _dispatchTool(name, args, sock);
  } catch (_te) {
    try {
      await _pconnEnsureRegistered(sock);
      await _pconnWrite({ cmd: 'publish', protocol: 'claws/2', topic: `tool.${name}.failed`, payload: { duration_ms: Date.now() - _t0, error: _te && _te.message || String(_te) } });
    } catch (_pe) { /* best-effort */ }
    throw _te;
  }
  try {
    await _pconnEnsureRegistered(sock);
    await _pconnWrite({ cmd: 'publish', protocol: 'claws/2', topic: `tool.${name}.completed`, payload: { duration_ms: Date.now() - _t0 } });
  } catch (_pe) { /* best-effort */ }
  return _r;
}

async function _dispatchTool(name, args, sock) {

  if (name === 'claws_list') {
    const resp = await clawsRpc(sock, { cmd: 'list' });
    if (!resp.ok) return toolError(`ERROR: ${resp.error}`);
    const terms = resp.terminals || [];
    if (!terms.length) return { content: [{ type: 'text', text: '[no terminals open]' }] };
    const lines = terms.map(t => {
      // R4: trust the `wrapped` boolean. Old code keyed off `logPath` which is
      // always null in the Pseudoterminal capture model — every wrapped
      // terminal was misreported as unwrapped.
      // Annotate pipe-mode degradation explicitly so the user sees it at a glance.
      let wrap;
      if (!t.wrapped) {
        wrap = 'unwrapped';
      } else if (t.ptyMode === 'pipe') {
        wrap = 'WRAPPED-DEGRADED-pipe-mode';
      } else if (t.ptyMode === 'pty') {
        wrap = 'WRAPPED';
      } else if (t.ptyMode === 'none') {
        wrap = 'WRAPPED-pending'; // pty.open() not called yet (panel hidden?)
      } else {
        wrap = 'WRAPPED';
      }
      const marker = t.active ? '*' : ' ';
      // R7: Pseudoterminal terminals report pid=-1 from VS Code's API
      // (VS Code didn't spawn the shell — we did). Prefer ptyPid.
      const realPid = (typeof t.ptyPid === 'number' && t.ptyPid > 0) ? t.ptyPid : t.pid;
      return `${marker} ${t.id}  ${(t.name || '').padEnd(25)} pid=${realPid}  [${wrap}]`;
    });
    return { content: [{ type: 'text', text: lines.join('\n') }] };
  }

  if (name === 'claws_create') {
    try { await _ensureSidecarOrThrow(); } catch (e) { return toolError('SPAWN REFUSED: sidecar unavailable — ' + e.message); }
    const _createCorrId = (typeof args.correlation_id === 'string' && args.correlation_id) ? args.correlation_id : randomUUID();
    const resp = await clawsRpc(sock, {
      cmd: 'create', name: args.name || 'claws',
      cwd: (typeof args.cwd === 'string' && args.cwd.length > 0) ? args.cwd : process.cwd(), wrapped: args.wrapped !== false, show: true,
    });
    if (!resp.ok) return toolError(`ERROR: ${_lifecycleErrMsg(resp.error)}`);
    const eventsLogPath = path.join(path.dirname(path.resolve(sock)), 'events.log');
    const _createTermId = resp.id;
    const _createMonitorCmd = `Monitor(command="CLAWS_TOPIC='system.worker.*' CLAWS_PEER_NAME='monitor-term-${_createTermId}' CLAWS_ROLE='observer' node ${path.join(path.dirname(path.resolve(sock)), '..', 'scripts', 'stream-events.js')} 2>&1 | grep --line-buffered '\\"correlation_id\\":\\"${_createCorrId}\\"' | grep --line-buffered -m1 'system\\\\.worker\\\\.completed'", description="claws monitor | term=${_createTermId} | corr=${_createCorrId.slice(0,8)} | sess=${new Date().toISOString().slice(0,13)}", timeout_ms=600000, persistent=false)`;
    // D+F: register spawn + monitor atomically before returning. Best-effort (lifecycle may not be in active mission).
    try { await clawsRpc(sock, { cmd: 'lifecycle.register-spawn', terminalId: String(_createTermId), correlationId: _createCorrId, name: args.name || 'claws' }); } catch (e) { /* lifecycle not initialized — non-fatal for claws_create */ }
    try { await clawsRpc(sock, { cmd: 'lifecycle.register-monitor', terminalId: String(_createTermId), correlationId: _createCorrId, command: _createMonitorCmd }); } catch (e) { /* non-fatal */ }
    const createResult = {
      ok: true, terminal_id: _createTermId,
      correlation_id: _createCorrId,
      ...(resp.logPath ? { log_path: resp.logPath } : {}),
      monitor_arm_required: true,
      monitor_arm_command: _createMonitorCmd,
      events_log_path: eventsLogPath,
    };
    return { content: [{ type: 'text', text: JSON.stringify(createResult, null, 2) }] };
  }

  if (name === 'claws_send') {
    // Auto-enable bracketed paste for multi-line text. Matches the documented
    // tool behavior and ensures the trailing CR registers as Enter in TUIs
    // like Claude Code (the extension splits the CR into a separate write
    // when bracketed paste is used; see claws-pty.ts:writeInjected).
    const text = args.text ?? '';
    const isMultiLine = text.includes('\n') || text.includes('\r');
    const resp = await clawsRpc(sock, {
      cmd: 'send', id: args.id, text,
      newline: args.newline !== false,
      paste: isMultiLine,
    });
    if (!resp.ok) return toolError(`ERROR: ${resp.error}`);
    return { content: [{ type: 'text', text: 'sent' }] };
  }

  if (name === 'claws_exec') {
    const timeoutMs = args.timeout_ms || 180000;
    return withMaxHold(
      fileExec(sock, args.id, args.command, timeoutMs).then((result) => {
        if (!result.ok) {
          let text = `ERROR: ${result.error}`;
          if (result.partial) text += `\n[partial output]\n${result.partial}`;
          return toolError(text);
        }
        return { content: [{ type: 'text', text: `exit ${result.exit_code}\n${result.output}` }] };
      }),
      8000,
      () => ({ content: [{ type: 'text', text: JSON.stringify({ ok: true, partial: true, hint: 'use claws_workers_wait to monitor' }) }] }),
    );
  }

  if (name === 'claws_read_log') {
    const resp = await clawsRpc(sock, { cmd: 'readLog', id: args.id, strip: true });
    if (!resp.ok) return toolError(`ERROR: ${resp.error}`);
    const allLines = (resp.bytes || '').split('\n');
    const n = args.lines || 50;
    const tail = allLines.length > n ? allLines.slice(-n) : allLines;
    const header = `[term ${args.id} · ${resp.totalSize || 0} bytes · showing last ${tail.length} of ${allLines.length} lines]`;
    return { content: [{ type: 'text', text: header + '\n' + tail.join('\n') }] };
  }

  if (name === 'claws_poll') {
    const resp = await clawsRpc(sock, { cmd: 'poll', since: args.since || 0 });
    if (!resp.ok) return toolError(`ERROR: ${resp.error}`);
    const events = resp.events || [];
    if (!events.length) return { content: [{ type: 'text', text: `[no events · cursor ${resp.cursor || 0}]` }] };
    const lines = events.map(e => {
      let line = `[seq ${e.seq} · ${e.terminalName} · exit ${e.exitCode}] $ ${e.commandLine || ''}`;
      if (e.output) {
        const out = e.output.length > 500 ? e.output.slice(0, 500) + '...' : e.output;
        line += '\n' + out;
      }
      return line;
    });
    return { content: [{ type: 'text', text: lines.join('\n') + `\n[cursor ${resp.cursor}]` }] };
  }

  if (name === 'claws_close') {
    const resp = await clawsRpc(sock, { cmd: 'close', id: args.id });
    if (!resp.ok) return toolError(`ERROR: ${resp.error}`);
    return { content: [{ type: 'text', text: `closed terminal ${args.id}` }] };
  }

  /**
   * claws_hello — register this Claude session with the Claws server.
   * Calls the claws/2 `hello` command. Must be invoked before any
   * subscribe/publish/task/broadcast call so the server can allocate a
   * stable peerId for this connection.
   * Role requirements: none (any role may hello).
   * Returns: peerId, serverCapabilities, orchestratorPresent.
   */
  if (name === 'claws_hello') {
    // Connect the persistent socket if not already connected. All subsequent
    // stateful calls (publish, subscribe, broadcast) share this socket so that
    // the server's per-connection peer state survives across tool calls.
    try {
      await _pconnEnsure(sock);
    } catch (err) {
      return toolError(`ERROR: cannot connect to Claws server: ${err.message}`);
    }
    const resp = await _pconnWrite({
      cmd: 'hello',
      protocol: 'claws/2',
      role: args.role,
      peerName: args.peerName,
      terminalId: args.terminalId,
      capabilities: Array.isArray(args.capabilities) ? args.capabilities : undefined,
    });
    if (!resp.ok) return toolError(`ERROR: ${resp.error || 'hello failed'}`);
    // Cache identity so we can re-register after a socket reconnect.
    _pconn.peerId = resp.peerId;
    _pconn.role = args.role;
    _pconn.peerName = args.peerName;
    _pconn.capabilities = Array.isArray(args.capabilities) ? args.capabilities : null;
    log(`registered as peer ${resp.peerId} role=${args.role}`);
    const out = {
      peerId: resp.peerId,
      serverCapabilities: resp.serverCapabilities || [],
      orchestratorPresent: !!resp.orchestratorPresent,
    };
    return { content: [{ type: 'text', text: JSON.stringify(out, null, 2) }] };
  }

  /**
   * claws_subscribe — subscribe this client to a topic pattern on the bus.
   * Calls the claws/2 `subscribe` command. Server-pushed frames for matching
   * topics will be delivered on this socket thereafter.
   * Role requirements: none (orchestrator, worker, and observer may all subscribe).
   * Returns: subscriptionId (opaque string used with unsubscribe).
   */
  if (name === 'claws_subscribe') {
    const resp = await clawsRpcStateful(sock, { cmd: 'subscribe', topic: args.topic });
    if (!resp.ok) return toolError(`ERROR: ${resp.error || 'subscribe failed'}`);
    return { content: [{ type: 'text', text: JSON.stringify({ subscriptionId: resp.subscriptionId, resumeCursor: resp.resumeCursor ?? null }, null, 2) }] };
  }

  /**
   * claws_publish — publish a payload to a topic on the Claws message bus.
   * Calls the claws/2 `publish` command. Delivered to every peer whose
   * subscription pattern matches the topic; the sender receives the message
   * too only when `echo: true`.
   * Role requirements: none (any peer may publish).
   * Returns: deliveredTo (number of subscribers who received the frame).
   */
  if (name === 'claws_publish') {
    const resp = await clawsRpcStateful(sock, {
      cmd: 'publish',
      topic: args.topic,
      payload: args.payload || {},
      echo: !!args.echo,
    });
    if (!resp.ok) return toolError(`ERROR: ${resp.error || 'publish failed'}`);
    return { content: [{ type: 'text', text: JSON.stringify({ deliveredTo: resp.deliveredTo || 0 }, null, 2) }] };
  }

  /**
   * claws_broadcast — orchestrator-only fan-out to all workers (or all peers).
   * Calls the claws/2 `broadcast` command. With `inject: true` the server also
   * sends the text into each target peer's associated terminal via bracketed
   * paste — this is the kill-switch path for workers that are deep in a tool
   * call and not reading their socket.
   * Role requirements: caller must have handshaked with role='orchestrator'.
   * Returns: deliveredTo (number of peers the broadcast reached).
   */
  if (name === 'claws_broadcast') {
    const resp = await clawsRpcStateful(sock, {
      cmd: 'broadcast',
      text: args.text,
      targetRole: args.targetRole || 'worker',
      inject: !!args.inject,
    });
    if (!resp.ok) return toolError(`ERROR: ${resp.error || 'broadcast failed'}`);
    return { content: [{ type: 'text', text: JSON.stringify({ deliveredTo: resp.deliveredTo || 0 }, null, 2) }] };
  }

  /**
   * claws_ping — liveness check.
   * Calls the claws/2 `ping` command. Also acts as an implicit heartbeat —
   * the server refreshes the caller's `lastSeen` so it is not reaped as
   * offline.
   * Role requirements: none.
   * Returns: serverTime (ms since epoch as reported by the server).
   */
  if (name === 'claws_ping') {
    const resp = await clawsRpc(sock, { cmd: 'ping' });
    if (!resp.ok) return toolError(`ERROR: ${resp.error || 'ping failed'}`);
    return { content: [{ type: 'text', text: JSON.stringify({ serverTime: resp.serverTime }, null, 2) }] };
  }

  /**
   * claws_peers — list all registered claws/2 peers.
   * There is no dedicated `peers` command on the server yet, so this tool
   * calls `introspect` and surfaces whatever peer info is included in the
   * snapshot (claws/2 Phase A exposes a peers map on the connection server).
   * Role requirements: none.
   * Returns: an array of peer records with { peerId, role, peerName, terminalId, lastSeen }.
   *
   * TODO: server-side 'peers' command needed in claws/2 Phase C — until then
   * we synthesise the list from `introspect` output. If the server already
   * has a `peers` command available we fall back to that first.
   */
  if (name === 'claws_peers') {
    // Prefer a direct `peers` command via the persistent socket (requires hello).
    // Fall back to `introspect` via a per-call socket for Phase C parity.
    let resp = await clawsRpcStateful(sock, { cmd: 'peers' });
    if (!resp.ok) {
      resp = await clawsRpc(sock, { cmd: 'introspect' });
    }
    if (!resp.ok) return toolError(`ERROR: ${resp.error || 'peers lookup failed'}`);
    const peers = resp.peers || (resp.snapshot && resp.snapshot.peers) || [];
    return { content: [{ type: 'text', text: JSON.stringify({ peers }, null, 2) }] };
  }

  if (name === 'claws_worker') {
    try { await _ensureSidecarOrThrow(); } catch (e) { return toolError('SPAWN REFUSED: sidecar unavailable — ' + e.message); }
    // Blocking mode: explicit wait:true OR detach:false are both treated as blocking.
    if (args.wait === true || args.detach === false) { // BUG-05: detach:false was ignored
      // Legacy blocking path — guarded at 8 s to protect MCP stdio.
      return withMaxHold(
        runBlockingWorker(sock, args).then((result) => {
          if (result.status === 'error') return toolError(`ERROR: ${result.error}`);
          const header = [
            `worker '${args.name}' ${result.status.toUpperCase()}`,
            `  terminal:   ${result.terminal_id}`,
            `  duration:   ${(result.duration_ms / 1000).toFixed(1)}s`,
            `  booted:     ${result.booted}`,
            `  cleaned_up: ${result.cleaned_up}`,
          ];
          if (result.marker_line) header.push(`  marker:     ${result.marker_line}`);
          if (result.status === 'spawned') {
            header.push('', `detached mode — use claws_read_log id=${result.terminal_id} and claws_close when done`);
            return { content: [{ type: 'text', text: header.join('\n') }] };
          }
          const body = result.harvest || '';
          return { content: [{ type: 'text', text: header.join('\n') + '\n\n── harvest (last lines) ──\n' + body }] };
        }),
        8000,
        () => ({ content: [{ type: 'text', text: JSON.stringify({ ok: true, partial: true, hint: 'use claws_workers_wait to monitor' }) }] }),
      );
    }

    // Non-blocking fast path (default) — boots terminal, sends mission, returns terminal_id immediately.
    const model = args.model || 'claude-sonnet-4-6';
    if (!/^[a-zA-Z0-9._-]+$/.test(model)) {
      return toolError(`ERROR: invalid model name '${model}' — must match /^[a-zA-Z0-9._-]+$/`);
    }
    const hasMission = typeof args.mission === 'string' && args.mission.length > 0;
    const hasCommand = typeof args.command === 'string' && args.command.length > 0;
    const launchClaude = args.launch_claude !== undefined ? !!args.launch_claude : hasMission;
    const workerCwd = typeof args.cwd === 'string' && args.cwd.length > 0 ? args.cwd : process.cwd();

    const cr = await clawsRpc(sock, {
      cmd: 'create', name: args.name || 'claws-worker', wrapped: true, show: true, cwd: workerCwd,
      env: { CLAWS_WORKER: '1' },
    });
    if (!cr.ok) return toolError(`ERROR: create failed: ${_lifecycleErrMsg(cr.error)}`);
    const termId = cr.id;
    const _fpCorrId = randomUUID();
    const _fpStartedAt = Date.now();

    // BUG-23: publish system.worker.spawned on non-blocking fast path — best-effort.
    try {
      await _pconnEnsureRegistered(sock);
      await _pconnWrite({
        cmd: 'publish', protocol: 'claws/2',
        topic: 'system.worker.spawned',
        payload: { terminal_id: termId, name: args.name || 'claws-worker', wrapped: true, started_at: new Date(_fpStartedAt).toISOString(), correlation_id: _fpCorrId },
      });
    } catch (e) { log('system.worker.spawned publish failed: ' + (e && e.message || e)); }

    // D+F: register spawn + monitor atomically. Best-effort (lifecycle may not be in active mission).
    try { await clawsRpc(sock, { cmd: 'lifecycle.register-spawn', terminalId: String(termId), correlationId: _fpCorrId, name: args.name || 'claws-worker' }); } catch (e) { /* non-fatal */ }
    const _fpMonitorCmd = `Monitor(command="CLAWS_TOPIC='system.worker.*' CLAWS_PEER_NAME='monitor-term-${termId}' CLAWS_ROLE='observer' node ${path.join(path.dirname(path.resolve(sock)), '..', 'scripts', 'stream-events.js')} 2>&1 | grep --line-buffered '\\"correlation_id\\":\\"${_fpCorrId}\\"' | grep --line-buffered -m1 'system\\\\.worker\\\\.completed'", description="claws monitor | term=${termId} | corr=${_fpCorrId.slice(0,8)} | sess=${new Date().toISOString().slice(0,13)}", timeout_ms=600000, persistent=false)`;
    try { await clawsRpc(sock, { cmd: 'lifecycle.register-monitor', terminalId: String(termId), correlationId: _fpCorrId, command: _fpMonitorCmd }); } catch (e) { /* non-fatal */ }

    await sleep(400);

    if (launchClaude) {
      await clawsRpc(sock, {
        cmd: 'send', id: termId,
        text: `claude --dangerously-skip-permissions --model ${model}`, newline: true,
      });
      // CRITICAL FIX (2026-05-02): wait for Claude TUI to be FULLY READY before
      // sending mission paste. Without this, mission lands in shell prompt while
      // Claude is still booting and the post-paste \r gets lost — mission sits
      // in input box forever, never submitted.
      // Event-driven: poll for ❯ (input prompt) + cost:$ (idle indicator).
      // Stable for 3 polls (~900ms) before declaring ready, then 5000ms settle.
      const _fpBootDeadline = Date.now() + (args.boot_wait_ms || 25000);
      let _fpStable = 0;
      while (Date.now() < _fpBootDeadline) {
        const _bs = await clawsRpc(sock, { cmd: 'readLog', id: termId, strip: true, limit: 32 * 1024 });
        const _bytes = (_bs.ok && typeof _bs.bytes === 'string') ? _bs.bytes : '';
        if (_bytes.includes('❯') && (_bytes.includes('cost:$') || _bytes.includes('cost: $'))) {
          _fpStable++;
          if (_fpStable >= 3) break;
        } else {
          _fpStable = 0;
        }
        await sleep(300);
      }
      // Post-readiness settle: Claude has hidden async window after ❯+cost:$.
      await sleep(5000);
    }

    const payload = hasMission
      ? args.mission.replace(/\x1b\[200~/g, '').replace(/\x1b\[201~/g, '')
      : hasCommand ? args.command : '';
    if (payload) {
      // Proven pattern from claws_dispatch_subworker (which submits reliably):
      //   paste:true newline:false  →  sleep(300)  →  explicit \r
      // The EXPLICIT CR after a 300ms gap is what actually submits — gives
      // Claude's React/Ink renderer time to close paste-mode state, then the
      // discrete \r registers as Enter (not as newline-within-input).
      const _missionPreSnap = await clawsRpc(sock, { cmd: 'readLog', id: termId, strip: true, limit: 32 * 1024 });
      const _missionPreLen = (_missionPreSnap.ok && typeof _missionPreSnap.bytes === 'string') ? _missionPreSnap.bytes.length : 0;
      await clawsRpc(sock, { cmd: 'send', id: termId, text: payload, newline: false, paste: true });
      await sleep(300);
      await clawsRpc(sock, { cmd: 'send', id: termId, text: '\r', newline: false });
      // Event-driven submit verification: poll for buffer growth (Claude processing).
      // If no growth in 5s, send another explicit CR nudge.
      const _submitDeadline = Date.now() + 5000;
      let _submitVerified = false;
      while (Date.now() < _submitDeadline) {
        await sleep(150);
        const _vs = await clawsRpc(sock, { cmd: 'readLog', id: termId, strip: true, limit: 32 * 1024 });
        if (_vs.ok && typeof _vs.bytes === 'string' && _vs.bytes.length > _missionPreLen + payload.length + 200) {
          _submitVerified = true; break;
        }
      }
      if (!_submitVerified) {
        log('mission submit not verified within 5s, sending another CR');
        await clawsRpc(sock, { cmd: 'send', id: termId, text: '\r', newline: false });
      }
    }

    // BUG-24+25: register detach watcher so system.worker.completed is published
    // and auto-close fires when complete_marker is detected — mirrors the
    // runBlockingWorker(detach:true) watcher but without boot-polling overhead.
    const _fpOpt = {
      complete_marker: typeof args.complete_marker === 'string' ? args.complete_marker : 'MISSION_COMPLETE',
      error_markers: Array.isArray(args.error_markers) ? args.error_markers : ['MISSION_FAILED'],
      timeout_ms: typeof args.timeout_ms === 'number' ? args.timeout_ms : 5 * 60 * 1000,
      poll_interval_ms: typeof args.poll_interval_ms === 'number' ? args.poll_interval_ms : 1500,
      close_on_complete: args.close_on_complete !== false,
    };
    let _fpScanOffset = 0;
    const _fpTick = async () => {
      try {
        if (Date.now() > _fpStartedAt + _fpOpt.timeout_ms) {
          clearInterval(_fpIntervalId);
          _detachWatchers.delete(termId);
          try {
            await _pconnEnsureRegistered(sock);
            await _pconnWrite({ cmd: 'publish', protocol: 'claws/2', topic: 'system.worker.completed',
              payload: { terminal_id: termId, status: 'timeout', duration_ms: Date.now() - _fpStartedAt, marker_line: null, booted: launchClaude, detach: true, correlation_id: _fpCorrId } });
          } catch (e) { log('fast-path watcher publish failed: ' + (e && e.message || e)); }
          try { await clawsRpc(sock, { cmd: 'lifecycle.mark-worker-status', terminalId: String(termId), status: 'timeout' }); } catch (e) { /* non-fatal */ }
          return;
        }
        const snap = await clawsRpc(sock, { cmd: 'readLog', id: termId, strip: true, limit: 64 * 1024 });
        const text = snap.ok && typeof snap.bytes === 'string' ? snap.bytes : '';
        if (text.length > _fpScanOffset) await _scanAndPublishCLAWSPUB(text.slice(_fpScanOffset), sock);
        _fpScanOffset = text.length;
        let _fpStatus = 'timeout';
        let _fpMarkerLine = null;
        const _fpCompleteLine = findStandaloneMarker(text, _fpOpt.complete_marker);
        if (_fpCompleteLine !== null) {
          _fpStatus = 'completed';
          _fpMarkerLine = _fpCompleteLine;
        } else {
          for (const em of _fpOpt.error_markers) {
            const _fpErrLine = em ? findStandaloneMarker(text, em) : null;
            if (_fpErrLine !== null) { _fpStatus = 'failed'; _fpMarkerLine = _fpErrLine; break; }
          }
        }
        if (_fpStatus !== 'timeout') {
          clearInterval(_fpIntervalId);
          _detachWatchers.delete(termId);
          try {
            await _pconnEnsureRegistered(sock);
            await _pconnWrite({ cmd: 'publish', protocol: 'claws/2', topic: 'system.worker.completed',
              payload: { terminal_id: termId, status: _fpStatus, duration_ms: Date.now() - _fpStartedAt, marker_line: _fpMarkerLine, booted: launchClaude, detach: true, correlation_id: _fpCorrId } });
          } catch (e) { log('fast-path watcher publish failed: ' + (e && e.message || e)); }
          try { await clawsRpc(sock, { cmd: 'lifecycle.mark-worker-status', terminalId: String(termId), status: _fpStatus }); } catch (e) { /* non-fatal */ }
          if (_fpOpt.close_on_complete) {
            try { await clawsRpc(sock, { cmd: 'close', id: termId }); } catch {}
          }
        }
      } catch (e) { log('fast-path watcher tick error: ' + (e && e.message || e)); }
    };
    const _fpIntervalId = setInterval(_fpTick, _fpOpt.poll_interval_ms);
    _detachWatchers.set(termId, { intervalId: _fpIntervalId, opt: _fpOpt, startedAt: _fpStartedAt });

    const run_token = randomUUID().slice(0, 12);
    const workerEventsLogPath = path.join(path.dirname(path.resolve(sock)), 'events.log');
    return {
      content: [{ type: 'text', text: JSON.stringify({
        ok: true, terminal_id: termId,
        name: args.name || 'claws-worker',
        correlation_id: _fpCorrId,
        run_token,
        hint: 'use claws_workers_wait to poll completion',
        monitor_arm_required: true,
        monitor_arm_command: _fpMonitorCmd,
        events_log_path: workerEventsLogPath,
      }, null, 2) }],
    };
  }

  if (name === 'claws_fleet') {
    try { await _ensureSidecarOrThrow(); } catch (e) { return toolError('SPAWN REFUSED: sidecar unavailable — ' + e.message); }
    const fleetWorkers = Array.isArray(args.workers) ? args.workers : [];
    if (fleetWorkers.length === 0) {
      return toolError('ERROR: workers must be a non-empty array of worker configs');
    }
    // detach default flipped to true in v0.7.10 — blocking mode unsafe over MCP stdio
    const detach = args.detach !== false;
    const sharedDefaults = {};
    for (const k of ['cwd', 'model', 'timeout_ms', 'boot_wait_ms', 'poll_interval_ms', 'harvest_lines', 'close_on_complete']) {
      if (args[k] !== undefined) sharedDefaults[k] = args[k];
    }
    const fleetStartedAt = Date.now();
    const fleetPromise = Promise.allSettled(
      fleetWorkers.map((w) => {
        const wClean = {};
        for (const [k, v] of Object.entries(w)) {
          if (v !== undefined) wClean[k] = v;
        }
        return runBlockingWorker(sock, { ...sharedDefaults, ...wClean, ...(detach ? { detach: true } : {}) });
      }),
    ).then((settled) => {
      const results = settled.map((s) => s.status === 'fulfilled'
        ? s.value
        : { status: 'error', error: String(s.reason && s.reason.message || s.reason || 'unknown') });
      const fleetEventsLogPath = path.join(path.dirname(path.resolve(sock)), 'events.log');
      const summary = {
        fleet_size: results.length,
        detach,
        wall_clock_ms: Date.now() - fleetStartedAt,
        max_individual_ms: Math.max(...results.map((r) => r.duration_ms || 0), 0),
        sum_individual_ms: results.reduce((a, r) => a + (r.duration_ms || 0), 0),
        workers: results.map((r, i) => {
          const _fTermId = r.terminal_id;
          const _fCorrId = r.correlation_id;
          return {
            name: fleetWorkers[i] && fleetWorkers[i].name,
            status: r.status,
            terminal_id: _fTermId,
            correlation_id: _fCorrId,
            duration_ms: r.duration_ms,
            marker_line: r.marker_line,
            monitor_arm_command: (_fTermId && _fCorrId)
              ? `Monitor(command="CLAWS_TOPIC='system.worker.*' CLAWS_PEER_NAME='monitor-term-${_fTermId}' CLAWS_ROLE='observer' node ${path.join(path.dirname(path.resolve(sock)), '..', 'scripts', 'stream-events.js')} 2>&1 | grep --line-buffered '\\"correlation_id\\":\\"${_fCorrId}\\"' | grep --line-buffered -m1 'system\\\\.worker\\\\.completed'", description="claws monitor | term=${_fTermId} | corr=${_fCorrId.slice(0,8)} | sess=${new Date().toISOString().slice(0,13)}", timeout_ms=600000, persistent=false)`
              : null,
          };
        }),
        monitor_arm_required: true,
        monitor_arm_command: 'arm one monitor_arm_command per worker entry above',
        events_log_path: fleetEventsLogPath,
      };
      return { content: [{ type: 'text', text: JSON.stringify(summary, null, 2) }] };
    });
    // Detach:true (default) returns quickly; detach:false legacy path gets the guard.
    return detach
      ? fleetPromise
      : withMaxHold(fleetPromise, 8000, () => ({
          content: [{ type: 'text', text: JSON.stringify({ ok: true, partial: true, hint: 'use claws_workers_wait to monitor' }) }],
        }));
  }

  if (name === 'claws_workers_wait') {
    const ids = Array.isArray(args.terminal_ids) ? args.terminal_ids : [];
    if (ids.length === 0) {
      return toolError('ERROR: terminal_ids must be a non-empty array');
    }
    const completeMarker = typeof args.complete_marker === 'string' && args.complete_marker.length > 0
      ? args.complete_marker : 'MISSION_COMPLETE';
    const errorMarkers = Array.isArray(args.error_markers) ? args.error_markers : ['MISSION_FAILED'];
    const timeoutMs = typeof args.timeout_ms === 'number' && args.timeout_ms > 0 ? args.timeout_ms : 5 * 60 * 1000;
    const pollIntervalMs = typeof args.poll_interval_ms === 'number' && args.poll_interval_ms > 0 ? args.poll_interval_ms : 1500;
    const startedAt = Date.now();
    const deadline = startedAt + timeoutMs;
    const state = ids.map((id) => ({
      id, status: 'pending', marker_line: null, duration_ms: null, scanFrom: 0,
    }));
    for (const s of state) {
      try {
        const snap = await clawsRpc(sock, { cmd: 'readLog', id: s.id, strip: true, limit: 64 * 1024 });
        if (snap.ok && typeof snap.bytes === 'string') s.scanFrom = snap.bytes.length;
      } catch (e) { /* keep 0 */ }
    }
    while (Date.now() < deadline) {
      let allDone = true;
      for (const s of state) {
        if (s.status !== 'pending') continue;
        allDone = false;
        try {
          const snap = await clawsRpc(sock, { cmd: 'readLog', id: s.id, strip: true, limit: 64 * 1024 });
          const text = snap.ok && typeof snap.bytes === 'string' ? snap.bytes : '';
          const scanText = text.length > s.scanFrom ? text.slice(s.scanFrom) : '';
          const _flCompleteLine = findStandaloneMarker(scanText, completeMarker);
          if (_flCompleteLine !== null) {
            s.status = 'completed';
            s.marker_line = _flCompleteLine;
            s.duration_ms = Date.now() - startedAt;
            continue;
          }
          for (const em of errorMarkers) {
            const _flErrLine = em ? findStandaloneMarker(scanText, em) : null;
            if (_flErrLine !== null) {
              s.status = 'failed';
              s.marker_line = _flErrLine;
              s.duration_ms = Date.now() - startedAt;
              break;
            }
          }
        } catch (e) { /* terminal vanished — leave pending; will time out */ }
      }
      if (allDone || state.every((s) => s.status !== 'pending')) break;
      await sleep(pollIntervalMs);
    }
    for (const s of state) {
      if (s.status === 'pending') {
        s.status = 'timeout';
        s.duration_ms = Date.now() - startedAt;
      }
    }
    return { content: [{ type: 'text', text: JSON.stringify({
      total: state.length,
      wall_clock_ms: Date.now() - startedAt,
      results: state.map((s) => ({ terminal_id: s.id, status: s.status, marker_line: s.marker_line, duration_ms: s.duration_ms })),
    }, null, 2) }] };
  }

  /**
   * claws_drain_events — drain buffered push frames from the persistent socket.
   * On first call, auto-subscribes to "**" (all topics) via the persistent socket
   * so subsequent frames are captured automatically. Returns events received since
   * since_index, with a dropped count for events that aged out of the ring buffer.
   * Set wait_ms > 0 to block until at least one new event arrives or the timer fires.
   */
  if (name === 'claws_drain_events') {
    const sinceIndex = typeof args.since_index === 'number' ? args.since_index : 0;
    const waitMs = typeof args.wait_ms === 'number' ? args.wait_ms : 0;
    const maxEvents = typeof args.max === 'number' ? args.max : 100;

    // Auto-subscribe on first call.
    if (!_eventBuffer.subscribed) {
      try {
        await _pconnEnsureRegistered(sock);
        const sr = await _pconnWrite({ cmd: 'subscribe', topic: '**' }, 5000);
        if (sr.ok) {
          _eventBuffer.subscribed = true;
          _eventBuffer.subscribeCursor = sr.resumeCursor ?? null;
        }
      } catch (err) {
        log('claws_drain_events: auto-subscribe failed: ' + (err && err.message || err));
      }
    }

    // If wait_ms > 0 and no new events yet, register a waiter.
    // Cap waiters at maxWaiters to prevent unbounded accumulation.
    const hasNew = () => _eventBuffer.ring.some(e => e.absoluteIndex > sinceIndex);
    if (waitMs > 0 && !hasNew()) {
      if (_eventBuffer.waiters.length >= _eventBuffer.maxWaiters) {
        return toolError('ERROR: drain waiter queue full (max 10 concurrent wait_ms requests)');
      }
      await new Promise((resolve) => {
        const timer = setTimeout(resolve, waitMs);
        _eventBuffer.waiters.push({ resolve, timer });
      });
    }

    const ring = _eventBuffer.ring;
    const totalReceived = _eventBuffer.totalReceived;
    const filtered = ring.filter(e => e.absoluteIndex > sinceIndex).slice(0, maxEvents);

    // dropped = events in [sinceIndex+1, ring[0].absoluteIndex - 1] that were evicted.
    let dropped = 0;
    if (ring.length > 0) {
      const firstInRing = ring[0].absoluteIndex;
      if (firstInRing > sinceIndex + 1) dropped = firstInRing - sinceIndex - 1;
    }

    return {
      content: [{
        type: 'text',
        text: JSON.stringify({ events: filtered, total_received: totalReceived, dropped, subscribe_cursor: _eventBuffer.subscribeCursor }, null, 2),
      }],
    };
  }

  if (name === 'claws_lifecycle_plan') {
    const _planMode = (typeof args.worker_mode === 'string') ? args.worker_mode : 'single';
    const _planExpected = (Number.isInteger(args.expected_workers) && args.expected_workers > 0) ? args.expected_workers : 1;
    const resp = await clawsRpc(sock, { cmd: 'lifecycle.plan', plan: args.plan, workerMode: _planMode, expectedWorkers: _planExpected });
    if (!resp.ok) return toolError(`ERROR: ${resp.error}\n${resp.message || ''}`);
    const out = { state: resp.state, idempotent: !!resp.idempotent };
    return { content: [{ type: 'text', text: JSON.stringify(out, null, 2) }] };
  }

  if (name === 'claws_lifecycle_advance') {
    const resp = await clawsRpc(sock, { cmd: 'lifecycle.advance', to: args.to, reason: args.reason });
    if (!resp.ok) return toolError(`ERROR: ${resp.error}\n${resp.message || ''}`);
    return { content: [{ type: 'text', text: JSON.stringify({ state: resp.state }, null, 2) }] };
  }

  if (name === 'claws_lifecycle_snapshot') {
    const resp = await clawsRpc(sock, { cmd: 'lifecycle.snapshot' });
    if (!resp.ok) return toolError(`ERROR: ${resp.error}`);
    const text = resp.state
      ? JSON.stringify(resp.state, null, 2)
      : '[no lifecycle state — call claws_lifecycle_plan first]';
    return { content: [{ type: 'text', text }] };
  }

  if (name === 'claws_lifecycle_reflect') {
    const resp = await clawsRpc(sock, { cmd: 'lifecycle.reflect', reflect: args.reflect });
    if (!resp.ok) return toolError(`ERROR: ${resp.error}\n${resp.message || ''}`);
    return { content: [{ type: 'text', text: JSON.stringify({ state: resp.state }, null, 2) }] };
  }

  if (name === 'claws_wave_create') {
    const resp = await clawsRpc(sock, {
      cmd: 'wave.create',
      waveId: args.waveId,
      layers: args.layers,
      manifest: args.manifest,
    });
    if (!resp.ok) return toolError(`ERROR: ${resp.error}`);
    return { content: [{ type: 'text', text: JSON.stringify({ waveId: resp.waveId, created: resp.created }, null, 2) }] };
  }

  if (name === 'claws_wave_status') {
    const resp = await clawsRpc(sock, { cmd: 'wave.status', waveId: args.waveId });
    if (!resp.ok) return toolError(`ERROR: ${resp.error}`);
    const tree = {
      waveId:              resp.waveId,
      complete:            resp.complete,
      lead:                resp.lead,
      subWorkers:          resp.subWorkers,
      subWorkerTerminals:  resp.subWorkerTerminals,
      orphanedTerminals:   resp.orphanedTerminals,
      harvestedAt:         resp.harvestedAt,
      layers:              resp.layers,
      createdAt:           resp.createdAt,
      completedAt:         resp.completedAt,
      summary:             resp.summary,
      commits:             resp.commits,
      regressionClean:     resp.regressionClean,
    };
    return { content: [{ type: 'text', text: JSON.stringify(tree, null, 2) }] };
  }

  if (name === 'claws_wave_complete') {
    const resp = await clawsRpc(sock, {
      cmd: 'wave.complete',
      waveId: args.waveId,
      summary: args.summary,
      commits: args.commits,
      regressionClean: args.regressionClean,
    });
    if (!resp.ok) return toolError(`ERROR: ${resp.error}`);
    return { content: [{ type: 'text', text: JSON.stringify({ waveId: resp.waveId, completedAt: resp.completedAt }, null, 2) }] };
  }

  if (name === 'claws_deliver_cmd') {
    const payload = typeof args.payload === 'string' ? JSON.parse(args.payload) : args.payload;
    const resp = await clawsRpcStateful(sock, {
      cmd: 'deliver-cmd',
      protocol: 'claws/2',
      targetPeerId: args.targetPeerId,
      cmdTopic: args.cmdTopic,
      payload,
      idempotencyKey: args.idempotencyKey,
    });
    if (!resp.ok && !resp.duplicate) return toolError(`ERROR: ${resp.error}`);
    return {
      content: [{
        type: 'text',
        text: JSON.stringify({
          ok: resp.ok,
          seq: resp.seq,
          duplicate: resp.duplicate ?? false,
        }, null, 2),
      }],
    };
  }

  if (name === 'claws_cmd_ack') {
    const resp = await clawsRpcStateful(sock, {
      cmd: 'cmd.ack',
      protocol: 'claws/2',
      seq: args.seq,
      status: args.status,
      ...(args.correlation_id ? { correlation_id: args.correlation_id } : {}),
    });
    if (!resp.ok) return toolError(`ERROR: ${resp.error}`);
    return { content: [{ type: 'text', text: JSON.stringify({ ok: true }, null, 2) }] };
  }

  if (name === 'claws_pipeline_create') {
    const steps = typeof args.steps === 'string' ? JSON.parse(args.steps) : args.steps;
    const resp = await clawsRpcStateful(sock, {
      cmd: 'pipeline.create',
      name: args.name || 'pipeline',
      steps,
    });
    if (!resp.ok) return toolError(`ERROR: ${resp.error}`);
    return {
      content: [{
        type: 'text',
        text: JSON.stringify({ pipelineId: resp.pipelineId, pipeline: resp.pipeline }, null, 2),
      }],
    };
  }

  if (name === 'claws_pipeline_list') {
    const resp = await clawsRpc(sock, { cmd: 'pipeline.list' });
    if (!resp.ok) return toolError(`ERROR: ${resp.error}`);
    return { content: [{ type: 'text', text: JSON.stringify(resp.pipelines, null, 2) }] };
  }

  if (name === 'claws_pipeline_close') {
    const resp = await clawsRpcStateful(sock, { cmd: 'pipeline.close', pipelineId: args.pipelineId }); // BUG-04: stateful socket carries peerId
    if (!resp.ok) return toolError(`ERROR: ${resp.error}`);
    return { content: [{ type: 'text', text: JSON.stringify({ ok: true, pipelineId: resp.pipelineId }, null, 2) }] };
  }

  if (name === 'claws_dispatch_subworker') {
    try { await _ensureSidecarOrThrow(); } catch (e) { return toolError('SPAWN REFUSED: sidecar unavailable — ' + e.message); }
    // FIX 3: Verify wave was created via claws_wave_create before spawning sub-worker.
    const waveCheck = await clawsRpc(sock, { cmd: 'wave.status', waveId: args.waveId });
    if (!waveCheck.ok && typeof waveCheck.error === 'string' && waveCheck.error.includes('not-found')) {
      return toolError(`SPAWN REFUSED: wave.not-registered — call claws_wave_create({waveId:'${args.waveId}', manifest:[...]}) first`);
    }
    const workerName = `wave-${args.waveId}-${args.role}`;
    const cr = await clawsRpc(sock, {
      cmd: 'create', name: workerName, wrapped: true, show: true,
      cwd: typeof args.cwd === 'string' && args.cwd.length > 0 ? args.cwd : process.cwd(),
      waveId: args.waveId, waveRole: args.role, env: { CLAWS_WORKER: '1' },
    });
    if (!cr.ok) return toolError(`ERROR: create failed: ${_lifecycleErrMsg(cr.error)}`);
    const termId = cr.id;
    const _dswCorrId = randomUUID();

    // BUG-A: publish system.worker.spawned for sub-workers — best-effort.
    log(`dispatch_subworker: publishing system.worker.spawned for terminal ${termId}`);
    try {
      await _pconnEnsureRegistered(sock);
      await _pconnWrite({
        cmd: 'publish', protocol: 'claws/2',
        topic: 'system.worker.spawned',
        payload: { terminal_id: termId, waveId: args.waveId, role: args.role, name: workerName, wrapped: true, started_at: new Date().toISOString(), correlation_id: _dswCorrId },
      });
      log(`dispatch_subworker: system.worker.spawned published ok for terminal ${termId}`);
    } catch (e) { log('dispatch_subworker: system.worker.spawned publish FAILED: ' + (e && e.message || e)); }

    // D+F: register spawn + monitor atomically. Best-effort (lifecycle may not be in active mission).
    try { await clawsRpc(sock, { cmd: 'lifecycle.register-spawn', terminalId: String(termId), correlationId: _dswCorrId, name: workerName }); } catch (e) { /* non-fatal */ }
    const _dswMonitorCmd = `Monitor(command="CLAWS_TOPIC='system.worker.*' CLAWS_PEER_NAME='monitor-term-${termId}' CLAWS_ROLE='observer' node ${path.join(path.dirname(path.resolve(sock)), '..', 'scripts', 'stream-events.js')} 2>&1 | grep --line-buffered '\\"correlation_id\\":\\"${_dswCorrId}\\"' | grep --line-buffered -m1 'system\\\\.worker\\\\.completed'", description="claws monitor | term=${termId} | corr=${_dswCorrId.slice(0,8)} | sess=${new Date().toISOString().slice(0,13)}", timeout_ms=600000, persistent=false)`;
    try { await clawsRpc(sock, { cmd: 'lifecycle.register-monitor', terminalId: String(termId), correlationId: _dswCorrId, command: _dswMonitorCmd }); } catch (e) { /* non-fatal */ }

    // BUG-08: fire-and-forget — return after create so parallel dispatch_subworker calls don't serialize.
    const _dswSock = sock;
    // GAP-D1: strip bracketed-paste escapes from mission to prevent keystroke injection.
    const _dswMission = (args.mission || '').replace(/\x1b\[200~/g, '').replace(/\x1b\[201~/g, '');
    const _dswWid = args.waveId;
    const _dswRole = args.role;
    // BUG-09: capture watcher options for auto-close watcher registered after mission send.
    const _dswCompleteMarker = typeof args.complete_marker === 'string' ? args.complete_marker : 'MISSION_COMPLETE';
    const _dswErrorMarkers = Array.isArray(args.error_markers) ? args.error_markers : ['MISSION_FAILED'];
    const _dswTimeoutMs = typeof args.timeout_ms === 'number' ? args.timeout_ms : 5 * 60 * 1000;
    const _dswPollMs = typeof args.poll_interval_ms === 'number' ? args.poll_interval_ms : 1500;
    const _dswCloseOnComplete = args.close_on_complete !== false;
    setImmediate(async () => {
      try {
        await sleep(400);
        await clawsRpc(_dswSock, {
          cmd: 'send', id: termId,
          text: 'claude --model claude-sonnet-4-6 --dangerously-skip-permissions', newline: true,
        });
        // Poll for trust prompt (~25 s), tracking log offset to avoid re-reading.
        let bootOk = false;
        let logOffset = 0;
        const bootDeadline = Date.now() + 25_000;
        while (Date.now() < bootDeadline) {
          const snap = await clawsRpc(_dswSock, { cmd: 'readLog', id: termId, strip: true, offset: logOffset, limit: 32 * 1024 });
          if (snap.ok && typeof snap.bytes === 'string') {
            if (snap.bytes.includes('trust')) { bootOk = true; break; }
            if (typeof snap.nextOffset === 'number') logOffset = snap.nextOffset;
          }
          await sleep(500);
        }
        if (!bootOk) log(`claws_dispatch_subworker: trust prompt not seen for ${workerName} — continuing anyway`);
        await clawsRpc(_dswSock, { cmd: 'send', id: termId, text: '1', newline: false });
        await sleep(1000);
        // GAP-D1: _dswMission already sanitized above — send as-is.
        // Single call: see claws_worker comment for rationale.
        await clawsRpc(_dswSock, { cmd: 'send', id: termId, text: _dswMission, newline: true, paste: true });

        // BUG-09: register auto-close watcher mirroring the fast-path detach watcher pattern.
        const _dswStartedAt = Date.now();
        let _dswScanOffset = 0;
        const _dswTick = async () => {
          try {
            if (Date.now() > _dswStartedAt + _dswTimeoutMs) {
              clearInterval(_dswIntervalId);
              _detachWatchers.delete(termId);
              try {
                await _pconnEnsureRegistered(_dswSock);
                await _pconnWrite({ cmd: 'publish', protocol: 'claws/2', topic: 'system.worker.completed',
                  payload: { terminal_id: termId, status: 'timeout', duration_ms: Date.now() - _dswStartedAt, marker_line: null, waveId: _dswWid, role: _dswRole, detach: true, correlation_id: _dswCorrId } });
              } catch (e) { log('dsw watcher publish failed: ' + (e && e.message || e)); }
              try { await clawsRpc(_dswSock, { cmd: 'lifecycle.mark-worker-status', terminalId: String(termId), status: 'timeout' }); } catch (e) { /* non-fatal */ }
              if (_dswCloseOnComplete) { try { await clawsRpc(_dswSock, { cmd: 'close', id: termId }); } catch {} }
              return;
            }
            const snap = await clawsRpc(_dswSock, { cmd: 'readLog', id: termId, strip: true, limit: 64 * 1024 });
            const text = snap.ok && typeof snap.bytes === 'string' ? snap.bytes : '';
            if (text.length > _dswScanOffset) await _scanAndPublishCLAWSPUB(text.slice(_dswScanOffset), _dswSock);
            _dswScanOffset = text.length;
            const scanText = text.slice(_dswScanOffset - Math.max(0, text.length - _dswScanOffset));
            let _dswStatus = null;
            let _dswMarkerLine = null;
            const _dswCompleteLine = findStandaloneMarker(text, _dswCompleteMarker);
            if (_dswCompleteLine !== null) {
              _dswStatus = 'completed';
              _dswMarkerLine = _dswCompleteLine;
            } else {
              for (const em of _dswErrorMarkers) {
                const _dswErrLine = em ? findStandaloneMarker(text, em) : null;
                if (_dswErrLine !== null) { _dswStatus = 'failed'; _dswMarkerLine = _dswErrLine; break; }
              }
            }
            if (_dswStatus) {
              clearInterval(_dswIntervalId);
              _detachWatchers.delete(termId);
              try {
                await _pconnEnsureRegistered(_dswSock);
                await _pconnWrite({ cmd: 'publish', protocol: 'claws/2', topic: 'system.worker.completed',
                  payload: { terminal_id: termId, status: _dswStatus, duration_ms: Date.now() - _dswStartedAt, marker_line: _dswMarkerLine, waveId: _dswWid, role: _dswRole, detach: true, correlation_id: _dswCorrId } });
              } catch (e) { log('dsw watcher publish failed: ' + (e && e.message || e)); }
              try { await clawsRpc(_dswSock, { cmd: 'lifecycle.mark-worker-status', terminalId: String(termId), status: _dswStatus }); } catch (e) { /* non-fatal */ }
              if (_dswCloseOnComplete) { try { await clawsRpc(_dswSock, { cmd: 'close', id: termId }); } catch {} }
            }
          } catch (e) { log('dsw watcher tick error: ' + (e && e.message || e)); }
        };
        const _dswIntervalId = setInterval(_dswTick, _dswPollMs);
        _detachWatchers.set(termId, { intervalId: _dswIntervalId, opt: { complete_marker: _dswCompleteMarker, error_markers: _dswErrorMarkers, timeout_ms: _dswTimeoutMs, poll_interval_ms: _dswPollMs, close_on_complete: _dswCloseOnComplete }, startedAt: _dswStartedAt });
      } catch (e) { log('claws_dispatch_subworker background boot error: ' + (e && e.message || e)); }
    });

    const dswEventsLogPath = path.join(path.dirname(path.resolve(sock)), 'events.log');
    return {
      content: [{
        type: 'text',
        text: JSON.stringify({
          terminal_id: termId, waveId: _dswWid, role: _dswRole, name: workerName,
          correlation_id: _dswCorrId,
          monitor_arm_required: true,
          monitor_arm_command: _dswMonitorCmd,
          events_log_path: dswEventsLogPath,
        }, null, 2),
      }],
    };
  }

  if (name === 'claws_schema_list') {
    const resp = await clawsRpc(sock, { cmd: 'schema.list', protocol: 'claws/2' });
    if (!resp.ok) return toolError(`ERROR: ${resp.error}`);
    return { content: [{ type: 'text', text: JSON.stringify({ schemas: resp.schemas }, null, 2) }] };
  }

  if (name === 'claws_schema_get') {
    const resp = await clawsRpc(sock, { cmd: 'schema.get', protocol: 'claws/2', name: args.name });
    if (!resp.ok) return toolError(`ERROR: ${resp.error}`);
    return { content: [{ type: 'text', text: JSON.stringify({ name: resp.name, schema: resp.schema }, null, 2) }] };
  }

  if (name === 'claws_rpc_call') {
    const resp = await clawsRpcStateful(sock, {
      cmd: 'rpc.call',
      protocol: 'claws/2',
      targetPeerId: args.targetPeerId,
      method: args.method,
      ...(args.params ? { params: args.params } : {}),
      ...(args.timeoutMs ? { timeoutMs: args.timeoutMs } : {}),
    });
    if (!resp.ok) return toolError(`ERROR: ${resp.error}`);
    return { content: [{ type: 'text', text: JSON.stringify({ requestId: resp.requestId, result: resp.result }, null, 2) }] };
  }

  if (name === 'claws_task_assign') {
    const resp = await clawsRpcStateful(sock, {
      cmd: 'task.assign', protocol: 'claws/2',
      title: args.title,
      assignee: args.assignee,
      prompt: args.prompt,
      ...(args.timeoutMs != null ? { timeoutMs: args.timeoutMs } : {}),
      ...(args.deliver ? { deliver: args.deliver } : {}),
    });
    if (!resp.ok) return toolError(`ERROR: ${resp.error || 'task.assign failed'}`);
    return { content: [{ type: 'text', text: JSON.stringify({ taskId: resp.taskId, assignedAt: resp.assignedAt }, null, 2) }] };
  }

  if (name === 'claws_task_update') {
    const resp = await clawsRpcStateful(sock, {
      cmd: 'task.update', protocol: 'claws/2',
      taskId: args.taskId,
      status: args.status,
      ...(args.progressPct != null ? { progressPct: args.progressPct } : {}),
      ...(args.note != null ? { note: args.note } : {}),
    });
    if (!resp.ok) return toolError(`ERROR: ${resp.error || 'task.update failed'}`);
    return { content: [{ type: 'text', text: JSON.stringify({ ok: true }, null, 2) }] };
  }

  if (name === 'claws_task_complete') {
    const resp = await clawsRpcStateful(sock, {
      cmd: 'task.complete', protocol: 'claws/2',
      taskId: args.taskId,
      status: args.status,
      ...(args.result != null ? { result: args.result } : {}),
      ...(args.artifacts != null ? { artifacts: args.artifacts } : {}),
    });
    if (!resp.ok) return toolError(`ERROR: ${resp.error || 'task.complete failed'}`);
    return { content: [{ type: 'text', text: JSON.stringify({ ok: true }, null, 2) }] };
  }

  if (name === 'claws_task_cancel') {
    const resp = await clawsRpcStateful(sock, {
      cmd: 'task.cancel', protocol: 'claws/2',
      taskId: args.taskId,
      ...(args.reason != null ? { reason: args.reason } : {}),
    });
    if (!resp.ok) return toolError(`ERROR: ${resp.error || 'task.cancel failed'}`);
    return { content: [{ type: 'text', text: JSON.stringify({ ok: true }, null, 2) }] };
  }

  if (name === 'claws_task_list') {
    const resp = await clawsRpcStateful(sock, {
      cmd: 'task.list', protocol: 'claws/2',
      ...(args.assignee ? { assignee: args.assignee } : {}),
      ...(args.status ? { status: args.status } : {}),
      ...(args.since != null ? { since: args.since } : {}),
    });
    if (!resp.ok) return toolError(`ERROR: ${resp.error || 'task.list failed'}`);
    return { content: [{ type: 'text', text: JSON.stringify({ tasks: resp.tasks || [] }, null, 2) }] };
  }

  return toolError(`unknown tool: ${name}`);
}

// ─── MCP server main loop ──────────────────────────────────────────────────

async function main() {
  process.stdin.resume();
  log('MCP server started, socket: ' + getSocket());

  while (true) {
    const msg = await readMessage();
    if (!msg) break;

    const { method, id, params = {} } = msg;

    if (method === 'initialize') {
      log('client connected: ' + ((params && params.clientInfo && params.clientInfo.name) || 'unknown'));
      respond(id, {
        protocolVersion: '2024-11-05',
        // Version must match extension/package.json — bump both together on release.
        serverInfo: { name: 'claws', version: '0.7.10' },
        capabilities: { tools: {} },
      });
    } else if (method === 'notifications/initialized') {
      // no response needed
    } else if (method === 'tools/list') {
      respond(id, { tools: TOOLS });
    } else if (method === 'tools/call') {
      // CONCURRENT TOOL DISPATCH (v0.7.10).
      // Do NOT await handleTool here — that would block the main loop and
      // serialize every tool call (the v0.7.4-through-v0.7.9 behavior).
      // When a long-running tool like claws_worker is in flight, fan-out
      // patterns (3 parallel workers, wave armies with 4 sub-workers, etc.)
      // would queue up behind it for up to timeout_ms each, defeating the
      // entire point of concurrent orchestration.
      //
      // Instead: dispatch the handler as a fire-and-forget Promise and let
      // the main loop immediately read the next message from stdin. Multiple
      // tool calls now interleave on the JS event loop, each progressing
      // whenever it await's I/O. State sharing is safe because:
      //   - _pconn requests use unique rids (nextRid++ is atomic in JS event loop)
      //   - _eventBuffer push is single-statement, never interleaved mid-write
      //   - _circuitBreaker fields are simple read/write, racy but benign
      //
      // respond() is called from the .then/.catch — JSON-RPC responses can
      // arrive out-of-order relative to the requests, which is allowed by
      // the spec (each response carries the matching id).
      handleTool(params.name || '', params.arguments || {})
        .then((result) => respond(id, result))
        .catch((e) => respond(id, {
          content: [{ type: 'text', text: `ERROR: ${e.message || e}` }],
          isError: true,
        }));
    } else if (method === 'ping') {
      respond(id, {});
    } else if (id != null) {
      respondError(id, -32601, `unknown method: ${method}`);
    }
  }
}

main().catch(console.error);
