// gen-docs.mjs — Regenerate the schema reference table in docs/event-protocol.md.
// Called by index.mjs. Default export is the generator function.
// Replaces content between <!-- BEGIN GENERATED SCHEMAS --> and
// <!-- END GENERATED SCHEMAS --> markers. If markers are absent, warns and
// exits without modifying the file.

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const BEGIN_MARKER = '<!-- BEGIN GENERATED SCHEMAS -->';
const END_MARKER   = '<!-- END GENERATED SCHEMAS -->';

const TOPIC_TABLE = `\
_This section is auto-generated by \`npm run schemas\` in \`extension/\`. Run to update._

| Topic Pattern | Schema Name | Key Required Fields |
|---|---|---|
| \`worker.*.boot\` | \`worker-boot-v1\` | model, role, mission_summary, cwd, terminal_id |
| \`worker.*.phase\` | \`worker-phase-v1\` | phase, prev, transition_reason, phases_completed |
| \`worker.*.event\` | \`worker-event-v1\` | kind, severity, message |
| \`worker.*.heartbeat\` | \`worker-heartbeat-v1\` | current_phase, time_in_phase_ms, tokens_used, cost_usd |
| \`worker.*.complete\` | \`worker-complete-v1\` | result, summary, artifacts, phases_completed |
| \`cmd.*.approve\` | \`cmd-approve-v1\` | correlation_id |
| \`cmd.*.reject\` | \`cmd-reject-v1\` | correlation_id, reason |
| \`cmd.*.abort\` | \`cmd-abort-v1\` | reason |
| \`cmd.*.pause\` | \`cmd-pause-v1\` | _(none)_ |
| \`cmd.*.resume\` | \`cmd-resume-v1\` | _(none)_ |
| \`cmd.*.set_phase\` | \`cmd-set-phase-v1\` | phase, reason |
| \`cmd.*.spawn\` | \`cmd-spawn-v1\` | name, mission |
| \`cmd.*.inject_text\` | \`cmd-inject-text-v1\` | text |
| \`system.peer.joined\` | \`system-peer-joined-v1\` | peerId, role, peerName, ts |
| \`system.peer.left\` | \`system-peer-left-v1\` | peerId, role, reason |
| \`system.peer.stale\` | \`system-peer-stale-v1\` | peerId, last_seen, missed_heartbeats |
| \`system.gate.fired\` | \`system-gate-fired-v1\` | tool, reason, peerId |
| \`system.budget.warning\` | \`system-budget-warning-v1\` | current_usd, threshold_usd |
| \`system.malformed.received\` | \`system-malformed-received-v1\` | from, topic, error |`;

export default async function genDocs(repoRoot) {
  const docPath = join(repoRoot, 'docs', 'event-protocol.md');
  let content;
  try {
    content = readFileSync(docPath, 'utf8');
  } catch {
    process.stderr.write(`[codegen/gen-docs] WARNING: docs/event-protocol.md not found — skipping\n`);
    return;
  }

  const beginIdx = content.indexOf(BEGIN_MARKER);
  const endIdx   = content.indexOf(END_MARKER);

  if (beginIdx === -1 || endIdx === -1) {
    process.stderr.write('[codegen/gen-docs] WARNING: markers not found in docs/event-protocol.md — skipping\n');
    return;
  }

  const before  = content.slice(0, beginIdx + BEGIN_MARKER.length);
  const after   = content.slice(endIdx);
  const updated = `${before}\n${TOPIC_TABLE}\n${after}`;
  writeFileSync(docPath, updated, 'utf8');
  console.log('[codegen/gen-docs] updated docs/event-protocol.md schema reference table');
}
